/* GROTA — English. Key = the Polish text exactly as in the code (see jezyk.js).
   Plural forms: "one|few|many" (Polish) → [one, other].
   Addresses and place names stay in Polish; quotes from the Polish government's "Poradnik bezpieczeństwa"
   (Safety Guide) are our translation — the app says so under every quote. */
(function (global) {
  "use strict";
  (global.GROTA_SLOWNIK = global.GROTA_SLOWNIK || {}).en = {
    "czas: sprawdź w Google Maps": "time: check in Google Maps",
    "ok. {m} min (szacunek)": "approx. {m} min (estimate)",
    "trasy i punkty: {osm} · schronienia: KG PSP, CC BY 4.0": "routes and points: {osm} · shelters: KG PSP, CC BY 4.0",
    "Punkty, Twoje miejsca i nagrane trasy działają. Wyszukiwarka adresów, wstępne trasy i zdjęcia z góry wrócą z siecią.": "Points, your places and recorded routes still work. Address search, draft routes and aerial photos will return when you are back online.",
    "Bez internetu · mapa uproszczona": "Offline · simplified map",
    "Odśwież": "Refresh",
    "Test bez internetu · mapa z pamięci telefonu": "Offline test · map from phone storage",
    "Bez internetu · mapa z pamięci telefonu": "Offline · map from phone storage",
    "Zakończ test": "End test",
    "Przygotowuję mapę… {p}%": "Preparing the map… {p}%",
    "Wczytuję punkty schronienia z całej Polski…": "Loading shelter points for all of Poland…",
    "Wczytuję punkty… {p}%": "Loading points… {p}%",
    "{s} s": "{s} s",
    "{m} min {s} s": "{m} min {s} s",
    "Nagrywam trasę": "Recording route",
    "czekam na GPS…": "waiting for GPS…",
    "do celu {d}": "{d} to go",
    "Słaby sygnał GPS — punkty pomijam, dopóki dokładność nie będzie lepsza niż {m} m.": "Weak GPS signal — points are skipped until accuracy is better than {m} m.",
    "Zakończ i zapisz": "Finish and save",
    "Anuluj": "Cancel",
    "Nagrywanie trasy wymaga lokalizacji (strona https albo localhost).": "Recording a route needs location access (https page or localhost).",
    "Nagrywanie trasy z „{n}” do: {a}.": "Recording a route from “{n}” to: {a}.",
    "Idź tak, jak szedłbyś w czasie alarmu — najkrótszą bezpieczną drogą, którą znasz. Nagrywanie działa tylko przy włączonym ekranie.": "Walk the way you would during an alert — the shortest safe route you know. Recording only works while the screen is on.",
    "Zacząć?": "Start?",
    "Nagrano za mało drogi, żeby zapisać trasę. Przerwać nagrywanie?": "Too little distance recorded to save a route. Stop recording?",
    "początek jest {d} od miejsca „{n}”": "the start is {d} from “{n}”",
    "koniec jest {d} od schronienia": "the end is {d} from the shelter",
    "Uwaga: {w}. Zapisać trasę mimo to?": "Note: {w}. Save the route anyway?",
    "Przerwać nagrywanie bez zapisu?": "Stop recording without saving?",
    "Trwa nagrywanie tej trasy — pasek nagrywania jest na mapie.": "This route is being recorded — the recording bar is on the map.",
    "Twoja trasa: {d} · {t}": "Your route: {d} · {t}",
    "nagrana {data} · {tryb} · w alarmie Grota pokaże ją zamiast wyliczonej": "recorded {data} · {tryb} · during an alert Grota shows it instead of a calculated one",
    "Przejdź tę drogę na próbę i nagraj ją. W alarmie Grota pokaże Twoją sprawdzoną trasę zamiast wyliczonej — także skróty, których nie ma w mapach.": "Walk this route as a practice run and record it. During an alert Grota will show your tested route instead of a calculated one — including shortcuts that maps don't know.",
    "Pokaż na mapie": "Show on map",
    "Nagraj ponownie": "Record again",
    "Nagraj swoją trasę": "Record your route",
    "Usuń nagraną trasę": "Delete recorded route",
    "Czas do zagrożenia to wyliczenie z zagrożeń widocznych w Strażniku. Alert RCB może dotyczyć czegoś, czego Strażnik nie widzi — wtedy realnie jest mniej czasu. Gdy przyszedł alert RCB albo słychać syreny, nie licz minut: działaj według komunikatu.": "The time to the threat is calculated from threats visible in Strażnik. A government RCB alert may concern something Strażnik cannot see — then there is really less time. If an RCB alert has arrived or you hear sirens, don't count minutes: follow the official message.",
    "Cel": "Goal",
    "Twoja nagrana trasa {d} · {t}": "Your recorded route {d} · {t}",
    "przećwiczona {data} ({tryb}) · pomarańczowa linia na mapie": "practised {data} ({tryb}) · orange line on the map",
    "Wyznaczam wstępną trasę…": "Calculating a draft route…",
    "Trasa {d} · ok. {m} min": "Route {d} · approx. {m} min",
    "policzona z mapy w telefonie — bez internetu, więc przybliżona": "calculated from the map on your phone — offline, so approximate",
    "Bez internetu nie da się wyznaczyć trasy po ulicach, a w pobranej mapie nie ma tu połączenia. Na mapie kierunek i odległość w linii prostej.": "Offline, a street route can't be calculated and the downloaded map has no connection here. The map shows direction and straight-line distance.",
    "Nie udało się wyznaczyć trasy (brak sieci?). Na mapie linia prosta — trasę pokaże Google Maps.": "Couldn't calculate a route (no network?). The map shows a straight line — Google Maps will show the route.",
    "po drogach i ścieżkach z mapy, bez korków i utrudnień · linia przerywana: kierunek w linii prostej · © OpenStreetMap, serwer tras FOSSGIS": "along roads and paths on the map, without traffic or obstacles · dashed line: straight-line direction · © OpenStreetMap, FOSSGIS routing server",
    "Tu jesteś": "You are here",
    "Pozycja jest bardzo przybliżona ({acc}). Wskaż swoje miejsce na mapie albo wybierz, gdzie jesteś.": "Your position is very approximate ({acc}). Point to your location on the map or choose where you are.",
    "Pozycja jest bardzo przybliżona ({acc}). Na komputerze bez GPS i Wi-Fi przeglądarka zgaduje miejsce z adresu internetowego — często wychodzi np. Warszawa. Wskaż swoje miejsce na mapie albo wybierz, gdzie jesteś.": "Your position is very approximate ({acc}). On a computer without GPS or Wi-Fi the browser guesses the location from the internet address — often Warsaw, for example. Point to your location on the map or choose where you are.",
    "Nowe położenie miejsca „{n}” jest daleko od zapisanych tu schronień (najbliższe {d} stąd).": "The new location of “{n}” is far from the shelters saved here (the nearest is {d} away).",
    "To schronienie zostanie usunięte z tego miejsca": "This shelter will be removed from this place",
    "Zapisane schronienia ({n}) zostaną usunięte z tego miejsca": "The saved shelters ({n}) will be removed from this place",
    ", razem z nagraną trasą": ", together with the recorded route",
    ", razem z nagranymi trasami ({n})": ", together with the recorded routes ({n})",
    "Punkty zostają na mapie — do nowego adresu wybierzesz schronienia na nowo.": "The points stay on the map — you will choose shelters again for the new address.",
    "Zmienić położenie?": "Change the location?",
    "„{tekst}”": "“{tekst}”",
    "„Poradnik bezpieczeństwa”, s. {s}": "Safety Guide (“Poradnik bezpieczeństwa”), p. {s}",
    "tłumaczenie nasze, oryginał po polsku": "our translation, original in Polish",
    "{n}: moje miejsce w budynku": "{n}: my spot in the building",
    "Sprawdzone przez Ciebie.": "Checked by you.",
    "Jeszcze nie sprawdzone na miejscu.": "Not yet checked on site.",
    "Zwiń": "Collapse",
    "Otwórz": "Open",
    "Zapisz jako schronienie dla:": "Save as a shelter for:",
    "To miejsce ma już 3 schronienia": "This place already has 3 shelters",
    "Zdjęcie z góry okolicy punktu": "Aerial photo of the area around the point",
    "Zdjęcie z góry niedostępne (brak sieci albo usługa GUGiK nie odpowiada).": "Aerial photo unavailable (no network or the GUGiK service is not responding).",
    "gm. {g}": "{g} municipality",
    "Jak wejść — godziny, kto otwiera, kontakt do zarządcy (Twoja notatka)": "How to get in — hours, who opens it, building manager's contact (your note)",
    "np. administrator osiedla, tel. …; otwarte 7–15": "e.g. estate administrator, phone …; open 7–15",
    "{d} od miejsca": "{d} from the place",
    "{d} od Ciebie": "{d} from you",
    "Przećwicz trasę": "Practise the route",
    "Prowadź": "Navigate",
    "Ustalam pozycję…": "Finding your position…",
    "Narysuj trasę tutaj, na mapie Groty": "Draw the route here, on Grota's map",
    "„Prowadź\" otwiera nawigację w telefonie. Bez internetu albo bez tej aplikacji nawigacja nie ruszy — wtedy ten guzik rysuje trasę orientacyjną na mapie Groty, z tego, co telefon ma u siebie.": "“Navigate” opens navigation on your phone. Without internet or without that app it won't start — then this button draws an approximate route on Grota's map from what the phone has stored.",
    "Skąd biorą się przesunięte punkty?": "Why are some points misplaced?",
    "Adresy i współrzędne pochodzą z publicznego zbioru Komendy Głównej PSP — tego samego, z którego korzystają inne aplikacje i serwisy. {ile} z {wszystkie} punktów ma oznaczone wątpliwe położenie: najczęściej szpilka stoi obok budynku — na podwórku, parkingu albo trawniku — rzadziej wskazuje miejsce poza miejscowością z adresu albo w innej gminie. <b>To błąd w danych źródłowych</b> i w tym, jak są dalej przetwarzane — nie w Grocie.": "Addresses and coordinates come from the public dataset of the National Headquarters of the State Fire Service (PSP) — the same one used by other apps and websites. {ile} of {wszystkie} points are marked as doubtful: most often the pin stands next to the building — in a yard, car park or lawn — less often it points outside the town in the address or to another municipality. <b>This is an error in the source data</b> and in how it is processed further — not in Grota.",
    "Grota takich punktów nie przesuwa po cichu ani nie ukrywa: oznacza je obwódką, nie poleca jako pierwszych i pisze, co stoi najbliżej szpilki. Szukaj w terenie tego budynku, nie samej szpilki.": "Grota doesn't silently move or hide such points: it marks them with an outline, doesn't suggest them first and says what stands nearest to the pin. On site, look for that building, not the pin itself.",
    "{n} pkt": "{n} pts",
    "Pokaż wszystkie": "Show all",
    "Rodzaj budynku (wg OpenStreetMap)": "Building type (per OpenStreetMap)",
    "Każdy przycisk włącza lub wyłącza swoją grupę. „Pokaż wszystkie” zaznacza wszystko, a naciśnięte ponownie — odznacza.": "Each button turns its group on or off. “Show all” selects everything; pressed again, it clears everything.",
    "Widać wszystkie punkty.": "All points are visible.",
    "Widać {n} z {wszystkie} punktów.": "{n} of {wszystkie} points are visible.",
    "Nic nie jest zaznaczone — mapa nie pokazuje żadnego punktu.": "Nothing is selected — the map shows no points.",
    "Filtr dotyczy tylko mapy — „Teraz” zawsze szuka wśród wszystkich sprawdzonych punktów.": "The filter only affects the map — “Now” always searches all verified points.",
    "Wybrany punkt": "Selected point",
    "Zamknij": "Close",
    "Zamknij kartę punktu": "Close the point card",
    "Czemu nie ma tu „schronów”?": "Why are there no “bunkers” here?",
    "Zamknij informację": "Close this note",
    "Publiczne dane PSP nie rozróżniają schronu, ukrycia i miejsca doraźnego schronienia — pełna ewidencja (CEOZO) z mocy ustawy nie jest informacją publiczną.": "Public PSP data doesn't distinguish a shelter (bunker), a hiding place and a makeshift shelter — the full register (CEOZO) is by law not public information.",
    "Wyjaśnienie i źródła": "Explanation and sources",
    "Filtry i widok": "Filters and view",
    "Środek transportu": "Means of transport",
    "Źródło: {zrodlo}; dane z {data}. Dane nie zawierają liczby miejsc ani rodzaju obiektu (schron / ukrycie / miejsce doraźne).": "Source: {zrodlo}; data from {data}. The data contains no capacity or type of facility (shelter / hiding place / makeshift shelter).",
    "Dotknij punktu na mapie — jego karta pojawi się tutaj.": "Tap a point on the map — its card will appear here.",
    "Wczytuję dane…": "Loading data…",
    "Zapisano": "Saved",
    "schronienia: {n}/3": "shelters: {n}/3",
    "nagrane trasy: {n}": "recorded routes: {n}",
    "wskazane na mapie": "picked on the map",
    "Położenie": "Location",
    "(przybliżone — popraw w „Edytuj”)": "(approximate — correct it in “Edit”)",
    "Moje miejsce w budynku": "My spot in the building",
    "· sprawdzone": "· checked",
    "· jeszcze nie sprawdzone": "· not yet checked",
    "nie zapisano": "not saved",
    "Edytuj dane miejsca": "Edit place details",
    "Moje miejsca schronienia ({n}/3)": "My shelters ({n}/3)",
    "Usuń z listy": "Remove from list",
    "Wybierz do trzech poniżej i przećwicz drogę — poradnik zaleca iść „ustaloną wcześniej drogą” (s. 34).": "Choose up to three below and practise the way — the guide recommends going “by a route agreed in advance” (p. 34).",
    "Wybierz miejsca schronienia": "Choose shelters",
    "Brak punktów spełniających filtr w pobliżu. Zaznacz więcej rodzajów powyżej.": "No points nearby match the filter. Select more types above.",
    "Nazwa": "Name",
    "Położenie przybliżone („{a}”) — wpisz dokładny adres albo wskaż budynek na mapie.": "Approximate location (“{a}”) — enter the exact address or point to the building on the map.",
    "Położenie przybliżone — wpisz dokładny adres albo wskaż budynek na mapie.": "Approximate location — enter the exact address or point to the building on the map.",
    "Moja pozycja": "My position",
    "Wskaż na mapie": "Pick on the map",
    "Kliknij na mapie nowe położenie miejsca „{n}”.": "Tap the new location of “{n}” on the map.",
    "Rodzaj miejsca": "Type of place",
    "Moje miejsce w tym budynku": "My spot in this building",
    "Twoja notatka, np. „korytarz na parterze, bez okien”": "Your note, e.g. “ground-floor corridor, no windows”",
    "Sprawdziłem to miejsce na miejscu": "I have checked this spot on site",
    "Środek transportu z tego miejsca": "Means of transport from this place",
    "Gotowe": "Done",
    "Przeciągnij, aby zmienić kolejność": "Drag to change the order",
    "Zmień kolejność: {n} (strzałki w górę i w dół)": "Change order: {n} (up and down arrows)",
    "Edytuj": "Edit",
    "Edytuj {n}": "Edit {n}",
    "Usuń miejsce": "Delete place",
    "Usuń miejsce {n}": "Delete place {n}",
    "Moje stałe miejsca": "My regular places",
    "Miejsca są zapisywane tylko na tym urządzeniu. Dotknij miejsca, aby zobaczyć szczegóły.": "Places are saved only on this device. Tap a place to see the details.",
    "Kolejność zmienisz, przeciągając kafel za uchwyt ⋮⋮.": "Change the order by dragging a tile by its ⋮⋮ handle.",
    "Nie masz jeszcze zapisanych miejsc — dodaj dom, pracę albo szkołę dziecka poniżej.": "You have no saved places yet — add your home, work or your child's school below.",
    "Dodaj miejsce": "Add a place",
    "Wybierz rodzaj. Pełny kolor — takie miejsce już masz.": "Choose a type. Full colour — you already have such a place.",
    "Nowe miejsce: {rodzaj}": "New place: {rodzaj}",
    "albo": "or",
    "Kliknij na mapie położenie miejsca „{n}”.": "Tap the location of “{n}” on the map.",
    "Wybrane przez Ciebie miejsce schronienia": "The shelter you chose",
    "Najbliższe sprawdzone miejsce schronienia": "Nearest verified shelter",
    "ok. {m} min trasą": "approx. {m} min by route",
    "PROWADŹ ➜": "NAVIGATE ➜",
    "Wybierz to miejsce: {a}": "Choose this place: {a}",
    "wg OpenStreetMap": "per OpenStreetMap",
    "Jestem w:": "I'm at:",
    "Pozycja z GPS": "GPS position",
    "Wpisz adres": "Enter an address",
    "Nic nie znalazłem. Spróbuj: „Miejscowość, ulica numer” albo samą miejscowość.": "Nothing found. Try “Town, street number” or just the town.",
    "Brak połączenia z wyszukiwarką adresów. Pokazuję miejscowości zapisane w aplikacji — pozycja to środek miejscowości.": "No connection to the address search. Showing towns stored in the app — the position is the town centre.",
    "Nie znalazłem tego adresu ani ulicy. Miejscowości o tej nazwie — to tylko środek miejscowości:": "Couldn't find this address or street. Towns with this name — this is only the town centre:",
    "Nie znalazłem tego adresu ani ulicy. Miejscowości o tej nazwie — to tylko środek miejscowości, po wyborze popraw położenie na mapie:": "Couldn't find this address or street. Towns with this name — this is only the town centre; after choosing, correct the location on the map:",
    "Dokładnego adresu nie ma w bazie adresów (np. numer mieszkania albo litera). Wyniki są przybliżone.": "The exact address isn't in the address database (e.g. a flat number or letter). The results are approximate.",
    "Dokładnego adresu nie ma w bazie adresów (np. numer mieszkania albo litera). Wyniki są przybliżone — po wyborze popraw położenie na mapie.": "The exact address isn't in the address database (e.g. a flat number or letter). The results are approximate — after choosing, correct the location on the map.",
    "np. Warszawa, Marszałkowska 100 · Zalesie Górne": "e.g. Warszawa, Marszałkowska 100 · Zalesie Górne",
    "Szukam…": "Searching…",
    "Szukaj": "Search",
    "Szukam od:": "Searching from:",
    "Zakończ": "Finish",
    "Poziom alarmu opiera się na źródłach pośrednich": "The alert level is based on indirect sources",
    "Nie ma teraz oficjalnego alertu RCB ani obiektu w powietrzu nad Polską. Grota pokazuje mapę, odległości i kierunki, ale <b>nie wzywa do schronienia</b> — kieruj się komunikatami służb, a jeśli ich nie ma, potraktuj to jako sygnał do uważności, nie do biegu.": "There is no official RCB alert or object in the air over Poland right now. Grota shows the map, distances and directions but <b>does not call you to take shelter</b> — follow official messages, and if there are none, treat this as a signal to stay alert, not to run.",
    "pieszo ok. {p} min · samochodem ok. {s} min": "on foot approx. {p} min · by car approx. {s} min",
    "To wyliczenie Groty, <b>nieoficjalne</b> — nie zastępuje komunikatów służb. Kieruj się w pierwszej kolejności oficjalnymi komunikatami (Alert RCB, RSO, radio, polecenia służb). Jeśli ich nie ma, potraktuj to jako podpowiedź.": "This is Grota's calculation, <b>unofficial</b> — it doesn't replace official messages. Follow official messages first (RCB Alert, RSO, radio, instructions from emergency services). If there are none, treat this as a hint.",
    "Umówione miejsce": "Meeting place",
    "Schowaj": "Hide",
    "Wskaż miejsce": "Set a place",
    "Jeśli umówiliście się z bliskimi na konkretne miejsce, wpisz je — Grota poprowadzi tam tak samo jak do schronienia i powie, czy zdążysz.": "If you have agreed on a specific place with your family, enter it — Grota will guide you there just like to a shelter and tell you whether you'll make it.",
    "To miejsce jest za daleko — {czasy}, a zagrożenie za {eta} min.": "This place is too far — {czasy}, and the threat is {eta} min away.",
    "Pieszo nie zdążysz — ok. {p} min przy zagrożeniu za {eta} min. Samochodem ok. {s} min.": "On foot you won't make it — approx. {p} min with the threat {eta} min away. By car approx. {s} min.",
    "To daleko — {czasy}. Sprawdź, czy zdążysz.": "That's far — {czasy}. Check whether you'll make it.",
    "To miejsce jest poza pobraną mapą.": "This place is outside the downloaded map.",
    "Zamknij ostrzeżenie": "Close the warning",
    "To miejsce jest <b>poza pobraną mapą</b> — bez internetu zobaczysz tam sam kierunek i odległość.": "This place is <b>outside the downloaded map</b> — offline you'll only see direction and distance there.",
    "Strażnik nie podaje teraz czasu do zagrożenia (sygnały są za stare albo kurs jest niepewny), więc Grota go nie zgaduje — porównaj sam z komunikatami służb.": "Strażnik isn't giving a time to the threat right now (the signals are too old or the heading is uncertain), so Grota doesn't guess it — compare with official messages yourself.",
    "Schowaj kroki": "Hide the steps",
    "Co robić teraz": "What to do now",
    "Usuń": "Delete",
    "Ustal swoją pozycję, żeby poznać odległość.": "Find your position to see the distance.",
    "Bez internetu i bez połączenia w pobranej mapie — na mapie kierunek i odległość w linii prostej.": "Offline and with no connection in the downloaded map — the map shows direction and straight-line distance.",
    "Nie udało się wyznaczyć trasy (brak sieci?). Na mapie linia prosta.": "Couldn't calculate a route (no network?). The map shows a straight line.",
    "— z mapy w telefonie": "— from the map on your phone",
    "Pokaż trasę": "Show route",
    "{km} km wokół Twojej pozycji": "{km} km around your position",
    "{km} km wokół: {n}": "{km} km around: {n}",
    "{km} km wokół miejsca": "{km} km around the place",
    "województwo {w}": "{w} province",
    "cała Polska": "all of Poland",
    "(mapa {m} + trasy {t})": "(map {m} + routes {t})",
    "pobierze {x}": "will download {x}",
    "zajmie w telefonie ok. {x}.": "will take approx. {x} on the phone.",
    "To, co już masz w telefonie, nie pobierze się drugi raz.": "Whatever is already on your phone won't be downloaded again.",
    "(sama mapa)": "(map only)",
    "Sprawdzam, jakie mapy są do pobrania…": "Checking which maps are available…",
    "Spróbuj ponownie": "Try again",
    "Wokół czego": "Around what",
    "mojej pozycji": "my position",
    "mojej pozycji (najpierw ustal pozycję)": "my position (find your position first)",
    "Dla tego miejsca nie ma jeszcze mapy do pobrania. Na razie dostępne: {lista}.": "There is no map to download for this place yet. Available for now: {lista}.",
    "Ustalam…": "Locating…",
    "Ustal pozycję": "Find position",
    "Albo wybierz wyżej jedno z zapisanych miejsc.": "Or choose one of your saved places above.",
    "Województwo": "Province",
    "— wybierz —": "— choose —",
    "Na razie do pobrania: {n} z {w} województw. Pozostałe dochodzą.": "Available for now: {n} of {w} provinces. The rest are coming.",
    "Pobieraj całą Polskę tylko przez wifi i tylko wtedy, gdy masz tyle wolnego miejsca w telefonie.": "Download all of Poland only over Wi-Fi and only if you have that much free space on your phone.",
    "Na razie w paczkach: {lista}.": "Packages available for now: {lista}.",
    "Przerwane. To, co zdążyło się pobrać, zostaje w telefonie — następna próba dobierze tylko resztę.": "Stopped. What was downloaded stays on the phone — the next attempt will fetch only the rest.",
    "kafelek mapy|kafelki mapy|kafelków mapy": ["map tile", "map tiles"],
    "obszaru|obszarów|obszarów": ["area", "areas"],
    "Pobrano {mb}: {kafelki} i dane do tras dla {obszary}.": "Downloaded {mb}: {kafelki} and route data for {obszary}.",
    "Pobrano {mb}: {kafelki}.": "Downloaded {mb}: {kafelki}.",
    "Wszystko było już w telefonie.": "Everything was already on the phone.",
    "oba motywy": "both themes",
    "jeden motyw": "one theme",
    "brak": "none",
    "Mapa offline": "Offline map",
    "Pobrane:": "Downloaded:",
    "element mapy|elementy mapy|elementów mapy": ["map item", "map items"],
    "styl mapy: {s}": "map style: {s}",
    "obszar|obszary|obszarów": ["area", "areas"],
    "dane do tras: {n}": "route data: {n}",
    "bez danych do tras": "no route data",
    "Przy alarmie sieć bywa przeciążona. Mapa pobrana wcześniej działa bez internetu — punkty schronienia i odległości działają zawsze, offline dochodzą do nich ulice.": "During an alert the network is often overloaded. A map downloaded in advance works offline — shelter points and distances always work; offline, streets are added to them.",
    "<b>Mapa offline to też miejsce dla innych.</b> W czasie alarmu z Groty korzystają tysiące osób naraz, a serwer jest jeden. Każdy, kto ma mapę w telefonie, zwalnia łącze komuś, kto nie zdążył jej pobrać.": "<b>An offline map also leaves room for others.</b> During an alert thousands of people use Grota at once, and there is one server. Everyone who has the map on their phone frees up bandwidth for someone who didn't manage to download it.",
    "Co pobrać": "What to download",
    "Mapa i trasy": "Map and routes",
    "Sama mapa": "Map only",
    "<b>Mapa i trasy.</b> Bez internetu Grota poprowadzi Cię ulicami i chodnikami do schronienia albo do umówionego miejsca. To jedyny wariant, który działa poza miastem: sama mapa ma jakąś trzecią część ścieżek, więc bez danych do tras na wsi zwykle nie ma z czego policzyć drogi.": "<b>Map and routes.</b> Offline, Grota will guide you along streets and pavements to a shelter or to your meeting place. This is the only option that works outside towns: the map alone has only about a third of the paths, so without route data there's usually nothing to calculate a route from in the countryside.",
    "<b>Sama mapa — mniejsza paczka.</b> Zobaczysz mapę, punkty schronienia i odległości, ale bez internetu Grota <b>nie wyznaczy trasy</b> — pokaże kierunek w linii prostej i budynki po drodze. W mieście to zwykle wystarcza, na wsi bywa za mało.": "<b>Map only — a smaller package.</b> You'll see the map, shelter points and distances, but offline Grota <b>won't calculate a route</b> — it shows the straight-line direction and the buildings on the way. In a town that's usually enough; in the countryside it may not be.",
    "Przerywam…": "Stopping…",
    "Sprawdzam, co jest do pobrania…": "Checking what to download…",
    "Pobieram wygląd mapy (kolory, ikony, napisy)…": "Downloading the map's look (colours, icons, labels)…",
    "Pobieram „{n}”: {x} z {razem}": "Downloading “{n}”: {x} of {razem}",
    "Możesz zamknąć tę kartę, ale nie aplikację. Po zerwaniu połączenia pobieranie samo spróbuje jeszcze raz.": "You can close this card, but not the app. If the connection drops, the download will retry by itself.",
    "Przerwij": "Stop",
    "Pobierz mapę": "Download map",
    "Sprawdź bez internetu": "Test offline",
    "dojście trasą ok. {d} min, zagrożenie za {eta} min": "route walk approx. {d} min, threat in {eta} min",
    "dojście ok. {d} min, zagrożenie za {eta} min": "walk approx. {d} min, threat in {eta} min",
    "Najpierw ustal pozycję (przycisk TERAZ, adres albo „Jestem w”) — wtedy symulacja porówna czas dojścia z czasem do zagrożenia.": "First find your position (NOW button, address or “I'm at”) — then the simulation will compare the time to get there with the time to the threat.",
    "Według szacunku nie zdążysz:": "By the estimate you won't make it:",
    "Na górze ekranu są zasady z poradnika na taką sytuację.": "At the top of the screen are the guide's rules for this situation.",
    "Według szacunku zdążysz: {zdanie}. To szacunek, nie gwarancja.": "By the estimate you'll make it: {zdanie}. This is an estimate, not a guarantee.",
    "Czas z alarmu Strażnika": "Time from Strażnik's alert",
    "Zagrożenie za <b>{eta} min</b> — ta sama wartość, którą pokazuje Strażnik.": "Threat in <b>{eta} min</b> — the same value Strażnik shows.",
    "Alarm opiera się na źródłach pośrednich, więc Grota nie porównuje go z czasem dojścia.": "The alert is based on indirect sources, so Grota doesn't compare it with the time to get there.",
    "Strażnik nie podaje teraz czasu do zagrożenia. Grota go nie zgaduje — pokazuje odległości i kierunek.": "Strażnik isn't giving a time to the threat right now. Grota doesn't guess it — it shows distances and direction.",
    "Symulacja ostrzeżenia Strażnika": "Strażnik alert simulation",
    "prototyp": "prototype",
    "Po połączeniu ze Strażnikiem czas przyjdzie z alarmu. Grota porówna go z czasem dojścia — jeśli nie zdążysz, zamiast prowadzić pokaże zasady z „Poradnika” (s. 29). Wybierz, za ile minut zagrożenie:": "Connected to Strażnik, the time comes from the alert. Grota compares it with the time to get there — if you won't make it, instead of guiding you it shows the rules from the guide (p. 29). Choose in how many minutes the threat arrives:",
    "Ustalam Twoją pozycję…": "Finding your position…",
    "Nie chcesz czekać? Wybierz, gdzie jesteś:": "Don't want to wait? Choose where you are:",
    "Dotknij mapy w miejscu, w którym jesteś.": "Tap the map where you are.",
    "Jesteś poza zasięgiem danych Groty.": "You are outside Grota's data coverage.",
    "Wybrane miejsce leży poza Polską.": "The chosen place is outside Poland.",
    "Według pozycji z telefonu jesteś poza Polską.": "According to your phone's position, you are outside Poland.",
    "Grota zna miejsca schronienia tylko w Polsce — najbliższe jest {d} stąd, więc nie wyznacza trasy. Poza Polską stosuj się do komunikatów tamtejszych służb.": "Grota only knows shelters in Poland — the nearest is {d} away, so it doesn't calculate a route. Outside Poland, follow the local authorities' instructions.",
    "Jesteś w Polsce, tuż przy granicy? Telefon mógł podać złą pozycję — wybierz, gdzie jesteś:": "Are you in Poland, right by the border? Your phone may have given a wrong position — choose where you are:",
    "Pokaż mimo to": "Show anyway",
    "Pozycja przybliżona ({acc}) — wynik może dotyczyć innego miejsca.": "Approximate position ({acc}) — the result may concern a different place.",
    "zagrożenie może być bliżej niż czas dojścia": "the threat may be closer than the time to get there",
    "To szacunek Groty, nie gwarancja — te same minuty pokazuje pasek na dole ekranu.": "This is Grota's estimate, not a guarantee — the bar at the bottom of the screen shows the same minutes.",
    "Wczytuję punkty schronienia — za chwilę pokażę najbliższe. Zasady niżej działają już teraz.": "Loading shelter points — I'll show the nearest in a moment. The rules below work already.",
    "Nie zaznaczono żadnego rodzaju dostępu — zaznacz co najmniej jeden powyżej.": "No access type is selected — select at least one above.",
    "punkt|punkty|punktów": ["point", "points"],
    "Bliżej jest {ile} o wątpliwym położeniu (najbliższy {d}) — Grota do nich nie prowadzi, bo szpilka stoi obok budynku albo w innym miejscu niż adres.": "There are {ile} with a doubtful location closer (the nearest {d}) — Grota doesn't guide you to them because the pin stands next to the building or somewhere other than the address.",
    "Inne opcje": "Other options",
    "GDZIE SIĘ SCHRONIĆ TERAZ": "WHERE TO TAKE SHELTER NOW",
    "Ustalę Twoją pozycję i wskażę najbliższe sprawdzone miejsce schronienia. Trasę poprowadzi Google Maps.": "I'll find your position and show the nearest verified shelter. Google Maps will guide you there.",
    "Pamiętaj — zasady z poradnika": "Remember — rules from the guide",
    "Przygotuj się": "Get prepared",
    "Listy są cytatem z „Poradnika bezpieczeństwa”. Zaznaczaj, co już masz — postęp zostaje tylko na tym urządzeniu.": "The lists quote the Safety Guide (“Poradnik bezpieczeństwa”). Tick what you already have — progress stays only on this device.",
    "Zrobione: {n} z {razem}.": "Done: {n} of {razem}.",
    "Miejsce w budynku dla domu, pracy i szkoły zapiszesz w zakładce „Moje miejsca”.": "You can save your spot in the building for home, work and school in the “My places” tab.",
    "Dodaj dom, pracę lub szkołę w zakładce „Moje miejsca” — zapiszesz tam też swoje miejsce w budynku.": "Add your home, work or school in the “My places” tab — you can also save your spot in the building there.",
    "Grota jest przetłumaczona przez autora aplikacji. Cytaty z „Poradnika bezpieczeństwa” to nasze tłumaczenie — oficjalny Poradnik jest tylko po polsku, a odnośniki prowadzą do polskiego oryginału. Adresy i nazwy miejsc zostają po polsku, tak jak na tabliczkach.": "Grota was translated by the app's author. Quotes from the Safety Guide (“Poradnik bezpieczeństwa”) are our translation — the official guide exists only in Polish, and the links lead to the Polish original. Addresses and place names stay in Polish, as on street signs.",
    "Zasady Groty": "Grota's rules",
    "Grota nie tworzy własnych procedur. Każde zalecenie pochodzi z „Poradnika bezpieczeństwa” (Rząd RP, nr publikacji 1/2025) i ma numer strony. Nazwy rozdziałów są z poradnika, podtytuły dodaliśmy sami, żeby odróżnić zalecenia z tego samego rozdziału.": "Grota doesn't create its own procedures. Every recommendation comes from the Safety Guide (“Poradnik bezpieczeństwa”, Government of Poland, publication no. 1/2025) and has a page number. Chapter names come from the guide; we added the subtitles ourselves to tell apart recommendations from the same chapter.",
    "Czego poradnik nie określa": "What the guide doesn't specify",
    "Poradnik nie podaje progu minut, po którym nie zdążysz dojść do schronienia, ani nie wskazuje środka transportu na czas ataku. Grota tego nie dopowiada: pokazuje szacunki i cytuje zasady.": "The guide gives no number of minutes after which you won't reach a shelter, and doesn't recommend a means of transport during an attack. Grota doesn't fill that in: it shows estimates and quotes the rules.",
    "Dlaczego w Grocie nie ma „schronów”": "Why Grota has no “bunkers”",
    "Inwentaryzacja Państwowej Straży Pożarnej z lat 2022–2023 wykazała w Polsce 1 903 schrony, 8 719 ukryć i 224 113 miejsc doraźnego schronienia. Publiczny zbiór „Punkty schronienia w Polsce”, na którym opiera się Grota, <b>nie rozróżnia tych kategorii</b> — wszystkie rekordy mają ten sam rodzaj.": "The State Fire Service inventory of 2022–2023 found 1,903 shelters (bunkers), 8,719 hiding places and 224,113 makeshift shelters in Poland. The public dataset “Shelter points in Poland” that Grota is based on <b>doesn't distinguish these categories</b> — all records have the same type.",
    "art. 113 ustawy o ochronie ludności i obronie cywilnej": "Article 113 of the Civil Protection and Civil Defence Act",
    "Art. 114": "Article 114",
    "Pełne dane, w tym rodzaj obiektu, pojemność i stan techniczny, trafiają do Centralnej Ewidencji Obiektów Zbiorowej Ochrony (CEOZO), którą prowadzi Komendant Główny PSP. Zgodnie z {a113} dane z tej ewidencji <b>nie są informacją publiczną</b>, a część z nich ma klauzulę „zastrzeżone”. {a114} przewiduje do wiadomości publicznej tylko ogólne dane dla województw i powiatów oraz informowanie o położeniu obiektów.": "The full data, including the type of facility, capacity and technical condition, goes to the Central Register of Collective Protection Facilities (CEOZO), kept by the Chief Commandant of the State Fire Service. Under {a113} data from this register <b>is not public information</b>, and part of it is classified as “restricted”. {a114} provides for publishing only general data for provinces and counties and informing about the location of facilities.",
    "Dlatego Grota pokazuje punkty schronienia bez etykiety „schron”. Oznaczanie ich na podstawie map społecznościowych byłoby zgadywaniem: obiekty opisane w OpenStreetMap jako bunkry to w większości fortyfikacje z wojen i ruiny. Jeśli PSP udostępni rodzaj obiektu, dodamy go razem z datą weryfikacji.": "That's why Grota shows shelter points without a “bunker” label. Marking them from community maps would be guesswork: objects tagged as bunkers in OpenStreetMap are mostly wartime fortifications and ruins. If the PSP publishes the type of facility, we'll add it together with the verification date.",
    "Źródła:": "Sources:",
    "ustawa z 5.12.2024 o ochronie ludności i obronie cywilnej": "Civil Protection and Civil Defence Act of 5.12.2024",
    "rozporządzenie MSWiA z 7.07.2025 o CEOZO": "Ministry of the Interior regulation of 7.07.2025 on CEOZO",
    "zbiór „Punkty schronienia w Polsce” na dane.gov.pl": "the “Shelter points in Poland” dataset on dane.gov.pl",
    "Twoje dane": "Your data",
    "Miejsca, notatki, nagrane trasy i ustawienia zapisują się <b>tylko w pamięci tego urządzenia</b>. Autor aplikacji ich nie widzi i nigdzie nie wysyła.": "Places, notes, recorded routes and settings are saved <b>only in this device's storage</b>. The app's author doesn't see them and doesn't send them anywhere.",
    "Kopia zapasowa iCloud może przenieść je na Twoje konto Apple.": "An iCloud backup may carry them to your Apple account.",
    "Kopia zapasowa Androida może przenieść je na Twoje konto Google.": "An Android backup may carry them to your Google account.",
    "Co opuszcza telefon i kiedy: wpisany adres trafia do wyszukiwarki GUGiK; przy wyznaczaniu trasy Twoja pozycja i cel idą do serwera tras FOSSGIS; współrzędne punktu do usługi zdjęć GUGiK; oglądany fragment mapy do OpenFreeMap; po naciśnięciu „Prowadź” albo „Street View” — do Google. Bez tych czynności nic nie wychodzi z telefonu.": "What leaves the phone and when: an address you type goes to the GUGiK address search; when a route is calculated, your position and destination go to the FOSSGIS routing server; a point's coordinates go to the GUGiK photo service; the part of the map you view goes to OpenFreeMap; after pressing “Navigate” or “Street View” — to Google. Without these actions nothing leaves the phone.",
    "Ograniczenia danych": "Data limitations",
    "Publiczny zbiór PSP nie podaje rodzaju obiektu, liczby miejsc ani tego, czy obiekt jest teraz otwarty. „Na żądanie” oznacza, że ktoś musi go otworzyć.": "The public PSP dataset gives neither the type of facility, nor its capacity, nor whether it's open right now. “On request” means someone has to open it.",
    "Położenie sprawdzamy automatycznie: czy punkt stoi na budynku, czy zgadza się z adresem, czy leży we właściwej gminie i województwie. Punkty wątpliwe (czerwona obwódka) nie są polecane jako pierwsze; „do sprawdzenia” (żółta) to drobniejsze rozbieżności. To nie jest kontrola obiektu przez urząd.": "We check the location automatically: whether the point stands on a building, matches the address, and lies in the right municipality and province. Doubtful points (red outline) aren't suggested first; “to check” (yellow) means minor discrepancies. This is not an official inspection of the facility.",
    "Przesunięte szpilki — błąd źródła, nie Groty": "Misplaced pins — a source error, not Grota's",
    "W publicznym zbiorze PSP część punktów ma współrzędne postawione obok budynku, którego dotyczą. Sprawdziliśmy to na danych z całej Polski: <b>1075 punktów</b> (1,3%) nie stoi na żadnym budynku. Przy 657 z nich budynek jest w promieniu 30 m (najczęściej blok — szpilka wylądowała na podwórku, parkingu albo trawniku), przy 252 w 30–60 m, przy 115 w 60–150 m, a <b>51 punktów nie ma żadnego budynku w promieniu 150 m</b> — tam szpilka wskazuje pole, las albo miejsce poza miejscowością z adresu.": "In the public PSP dataset some points have coordinates placed next to the building they refer to. We checked this on data for all of Poland: <b>1,075 points</b> (1.3%) don't stand on any building. For 657 of them a building is within 30 m (most often a block of flats — the pin landed in a yard, car park or lawn), for 252 within 30–60 m, for 115 within 60–150 m, and <b>51 points have no building within 150 m</b> — there the pin points to a field, a forest or a place outside the town in the address.",
    "To błąd danych źródłowych i ich dalszego przetwarzania, nie Groty. Nie przesuwamy punktów po cichu, bo nie mamy czym potwierdzić, gdzie naprawdę jest schronienie. Zamiast tego: oznaczamy je, nie polecamy jako pierwszych i przy każdym piszemy, co stoi najbliżej szpilki i jak daleko — żeby w terenie szukać budynku, a nie kropki na mapie.": "This is an error in the source data and its further processing, not in Grota. We don't silently move points because we have no way to confirm where the shelter really is. Instead we mark them, don't suggest them first, and for each one we say what stands nearest to the pin and how far — so that on site you look for the building, not the dot on the map.",
    "Jeśli widzisz punkt postawiony w złym miejscu, zgłoś to gminie albo komendzie PSP, która przekazuje dane do zbioru — poprawka u źródła naprawia go we wszystkich aplikacjach naraz.": "If you see a point in the wrong place, report it to the municipality or to the PSP command that submits the data — a fix at the source corrects it in all apps at once.",
    "Czas dojścia to szacunek: zanim trasa się wyznaczy — z odległości w linii prostej, potem z trasy po drogach i ścieżkach (bez korków i utrudnień). Nie jest gwarancją.": "The time to get there is an estimate: before a route is calculated — from the straight-line distance, then from the route along roads and paths (without traffic or obstacles). It's not a guarantee.",
    "Źródła": "Sources",
    "wersja internetowa na gov.pl": "online version on gov.pl",
    "Zasady i listy kontrolne: {autorzy}, „{tytul}”, {wydanie}, {wersja}, licencja {licencja}.": "Rules and checklists: {autorzy}, “{tytul}”, {wydanie}, {wersja}, licence {licencja}.",
    "{zrodlo}; dane z {data}. Kontrola budynków: {kontrola}. Mapa: OpenFreeMap, © OpenStreetMap. Zdjęcia z góry: ortofotomapa GUGiK (usługa WMS, pobierana na bieżąco, bez zapisywania). Biblioteka mapy: MapLibre (BSD).": "{zrodlo}; data from {data}. Building check: {kontrola}. Map: OpenFreeMap, © OpenStreetMap. Aerial photos: GUGiK orthophoto map (WMS service, fetched live, never stored). Map library: MapLibre (BSD).",
    "Wyszukiwanie adresów: usługa geokodowania GUGiK (zapytanie wysyłane dopiero po naciśnięciu „Szukaj”). Spis miejscowości do wyszukiwania bez internetu: OpenStreetMap (© współtwórcy OSM, ODbL). Ikony: Lucide (licencja ISC).": "Address search: GUGiK geocoding service (the query is sent only after pressing “Search”). List of towns for offline search: OpenStreetMap (© OSM contributors, ODbL). Icons: Lucide (ISC licence).",
    "Wstępna trasa na mapie: serwer tras FOSSGIS (OSRM, dane © współtwórcy OpenStreetMap) — pozycja i cel są wysyłane do tego serwera; trasa nie uwzględnia korków ani utrudnień.": "Draft route on the map: FOSSGIS routing server (OSRM, data © OpenStreetMap contributors) — your position and destination are sent to this server; the route doesn't account for traffic or obstacles.",
    "Popraw mapę": "Fix the map",
    "Rodzaj budynku (szkoła, blok, parking podziemny…): OpenStreetMap, nie dane PSP.": "Building type (school, block of flats, underground car park…): OpenStreetMap, not PSP data.",
    "„W określonych godzinach” i „na żądanie”": "“During set hours” and “on request”",
    "Według komunikatów PSP i samorządów o aplikacji „Gdzie się ukryć”: obiekty z godzinami są dostępne w czasie pracy placówki lub obecności obsługi, a obiekty „na żądanie” są zamknięte (np. piwnice bloków, garaże wspólnot) i w razie zagrożenia powinni je otworzyć zarządcy lub mieszkańcy w ramach wzajemnej pomocy. Publiczne dane nie podają godzin ani kontaktu — zapytaj zarządcę budynku zawczasu i zapisz odpowiedź przy swoim miejscu schronienia.": "According to PSP and local government announcements about the “Gdzie się ukryć” (Where to hide) app: facilities with hours are accessible during the institution's working hours or when staff are present, and “on request” facilities are locked (e.g. basements of blocks of flats, residents' garages) and in an emergency should be opened by the managers or residents as mutual help. Public data gives no hours or contacts — ask the building manager in advance and note the answer with your shelter.",
    "brak w pobliżu": "none nearby",
    "Rodzaj budynku: wszystkie": "Building type: all",
    "Rodzaj budynku: {n} z {w}": "Building type: {n} of {w}",
    "zapisuję…": "saving…",
    "Wpisz adres albo wskaż miejsce na mapie.": "Enter an address or pick the place on the map.",
    "Usunąć nagraną trasę?": "Delete the recorded route?",
    "Możesz też ustalić pozycję na ekranie TERAZ albo wskazać ją na mapie.": "You can also find your position on the NOW screen or pick it on the map.",
    "Usunąć miejsce „{n}” razem z zapisanymi schronieniami i notatkami?": "Delete the place “{n}” together with its saved shelters and notes?",
    "Wskaż miejsce na mapie.": "Pick the place on the map.",
    "zapisane miejsce „{n}”": "saved place “{n}”",
    "Wczytuję punkty schronienia…": "Loading shelter points…",
    "budynek": "building",
    "nie ma żadnego budynku w promieniu 150 m — współrzędne są prawdopodobnie błędne": "there's no building within 150 m — the coordinates are probably wrong",
    "szpilka stoi obok budynku, nie na nim — najbliżej {co}, {m} m stąd": "the pin stands next to a building, not on it — nearest: {co}, {m} m away",
    "szpilka nie stoi przy żadnym budynku — najbliższy ({co}) jest {m} m stąd": "the pin isn't next to any building — the nearest ({co}) is {m} m away",
    "punkt leży w innym województwie niż podane w danych": "the point lies in a different province than the data says",
    "innej gminie": "another municipality",
    "dane podają gminę {g}, a punkt leży w: {gdzie}": "the data gives the municipality {g}, but the point lies in: {gdzie}",
    "adres z danych jest {km} km od punktu": "the address in the data is {km} km from the point",
    "adres z danych jest {m} m od punktu — sprawdź na miejscu": "the address in the data is {m} m from the point — check on site",
    "miejscowość o tej nazwie jest {km} km dalej (nazwy bywają powtarzalne)": "a town with this name is {km} km away (names repeat)",
    "dane PSP nie podają gminy": "PSP data gives no municipality",
    "Położenie wątpliwe: {co}.": "Doubtful location: {co}.",
    "Do sprawdzenia: {co}.": "To check: {co}.",
    "Położenie sprawdzone automatycznie: punkt stoi na budynku, zgadza się z adresem.": "Location checked automatically: the point stands on a building and matches the address.",
    "Położenie sprawdzone automatycznie: punkt stoi na budynku.": "Location checked automatically: the point stands on a building.",
    "Położenie sprawdzone automatycznie: punkt {m} m od budynku, zgadza się z adresem.": "Location checked automatically: the point is {m} m from a building and matches the address.",
    "Położenie sprawdzone automatycznie: punkt {m} m od budynku.": "Location checked automatically: the point is {m} m from a building.",
    "nr {n}": "no. {n}",
    "pow. {p}": "{p} county",
    "cała ulica — pozycja przybliżona": "whole street — approximate position",
    "tego numeru nie ma w bazie adresów — sprawdź położenie na mapie": "this number isn't in the address database — check the location on the map",
    "Bez internetu nie sprawdzę, jakie mapy są do pobrania.": "Offline I can't check which maps are available.",
    "Serwer map nie podał spisu (kod {k}).": "The map server didn't return the list (code {k}).",
    "Serwer map podał spis w nieznanym formacie.": "The map server returned the list in an unknown format.",
    "serwer nie obsługuje pobierania zakresami": "the server doesn't support range downloads",
    "kod {k}": "code {k}",
    "paczka na serwerze nie zgadza się ze spisem": "the package on the server doesn't match the list",
    "niepełny kawałek": "incomplete chunk",
    "brak połączenia": "no connection",
    "Nie udało się pobrać fragmentu mapy ({powod}).": "Couldn't download part of the map ({powod}).",
    "Paczka na serwerze ma nieznany format.": "The package on the server has an unknown format.",
    "Pobrany fragment mapy jest uszkodzony — spróbuj jeszcze raz.": "The downloaded part of the map is damaged — try again.",
    "Pieszo": "On foot",
    "Rower / hulajnoga": "Bike / scooter",
    "Rower": "Bike",
    "Samochód / motocykl": "Car / motorbike",
    "Samochód": "Car",
    "Całodobowo": "24 hours",
    "Według PSP obiekt jest dostępny całą dobę.": "According to the PSP the facility is accessible around the clock.",
    "W określonych godzinach": "During set hours",
    "Dostępny tylko w godzinach pracy obiektu lub obecności obsługi. Godzin nie ma w publicznych danych — sprawdź je wcześniej u zarządcy.": "Accessible only during the facility's working hours or when staff are present. The hours aren't in the public data — check them with the manager in advance.",
    "Na żądanie": "On request",
    "Obiekt zamknięty (np. piwnica bloku, garaż). Zarządca lub mieszkańcy powinni go otworzyć w razie zagrożenia — nie zakładaj, że będzie otwarty. Zapytaj zarządcę wcześniej.": "A locked facility (e.g. a basement of a block of flats, a garage). The manager or residents should open it in an emergency — don't assume it will be open. Ask the manager in advance.",
    "Brak informacji": "No information",
    "Dom": "Home",
    "Praca": "Work",
    "Szkoła / uczelnia": "School / university",
    "Przedszkole / żłobek": "Kindergarten / nursery",
    "Rodzina / bliscy": "Family / relatives",
    "Działka / domek": "Allotment / cottage",
    "Inne": "Other",
    "Sygnały alarmowe i komunikaty ostrzegawcze": "Alarm signals and warning messages",
    "co robić po usłyszeniu sygnału": "what to do when you hear the signal",
    "Jeśli usłyszysz sygnał alarmowy, włącz radio lub telewizor i stosuj się do komunikatów.": "If you hear an alarm signal, turn on the radio or TV and follow the announcements.",
    "Atak z powietrza": "Air attack",
    "droga do schronienia": "the way to the shelter",
    "Kiedy usłyszysz sygnał alarmowy, idź ustaloną wcześniej drogą ewakuacyjną do miejsca schronienia. Zabierz ze sobą plecak ewakuacyjny. Unikaj wind, idź schodami. Schronienie, do którego się udajesz, powinno być bez okien, mieć grube ściany, gruby strop, dostęp do powietrza i wyjście awaryjne.": "When you hear an alarm signal, take the evacuation route agreed in advance to the shelter. Take your emergency backpack with you. Avoid lifts, use the stairs. The shelter you go to should have no windows, thick walls, a thick ceiling, access to air and an emergency exit.",
    "Schronienia": "Shelters",
    "gdy nie zdążysz do punktu schronienia": "if you can't reach a shelter point in time",
    "Jeśli nie możesz ukryć się w oznaczonym miejscu schronienia, zostań w domu – z dala od okien, przy ścianach nośnych, w centralnych pomieszczeniach.": "If you can't hide in a marked shelter, stay at home – away from windows, by load-bearing walls, in central rooms.",
    "gdy jesteś poza domem": "if you are away from home",
    "Jeśli jesteś poza domem, szukaj miejsc, które zapewniają przynajmniej minimum ochrony (najniższe kondygnacje budynków, w tym piwnice, garaże podziemne, tunele, przejścia podziemne). Nawet zwykłe zagłębienia terenu zapewniają lepszą ochronę niż przebywanie na otwartej przestrzeni.": "If you are away from home, look for places that give at least minimal protection (the lowest floors of buildings, including basements, underground garages, tunnels, underpasses). Even ordinary dips in the ground give better protection than staying in the open.",
    "eksplozja w otwartym terenie": "an explosion in the open",
    "Jeśli na otwartym terenie usłyszysz eksplozję, padnij na ziemię – najlepiej w zagłębieniu – i osłoń głowę.": "If you hear an explosion in the open, drop to the ground – ideally in a dip – and cover your head.",
    "po ataku": "after the attack",
    "Nie wychodź ze schronienia pochopnie. Nie przeciążaj linii telefonicznych – korzystaj z SMS-ów. Pomóż innym – sprawdź, kto wokół Ciebie potrzebuje wsparcia.": "Don't leave the shelter hastily. Don't overload phone lines – use text messages. Help others – check who around you needs support.",
    "Przygotuj swoje otoczenie — Transport": "Prepare your surroundings — Transport",
    "samochód w kryzysie": "the car in a crisis",
    "W sytuacjach kryzysowych ogranicz korzystanie z samochodu. Drogi powinny być przejezdne dla służb ratowniczych i transportów wojskowych. Miej przy sobie papierową mapę lub atlas samochodowy. Możesz wcześniej pobrać mapy offline. System GPS może nie działać.": "In crisis situations limit your use of the car. Roads should stay passable for emergency services and military transport. Keep a paper map or road atlas with you. You can download offline maps in advance. GPS may not work.",
    "Ewakuacja": "Evacuation",
    "gdy służby zarządzą ewakuację": "when the authorities order an evacuation",
    "Jeżeli władze lub służby ratownicze zdecydują o ewakuacji, bezwzględnie zastosuj się do poleceń. Informacje będziesz dostawać na bieżąco ze stron rządowych, Alertów RCB, RSO i mediów.": "If the authorities or emergency services decide on an evacuation, follow their instructions without fail. You will get up-to-date information from government websites, RCB Alerts, RSO and the media.",
    "gdzie szukać miejsc schronienia": "where to find shelters",
    "Informacje o lokalizacji miejsc schronienia znajdziesz w urzędzie gminy, jednostce Państwowej lub Ochotniczej Straży Pożarnej oraz na stronie gov.pl/kgpsp. Schronienia są oznaczone specjalnym znakiem graficznym.": "You can find information on shelter locations at the municipal office, at a State or Volunteer Fire Service station and at gov.pl/kgpsp. Shelters are marked with a special sign.",
    "Dekalog bezpieczeństwa": "Safety decalogue",
    "punkt z dekalogu": "a point from the decalogue",
    "Sprawdź, gdzie jest najbliższe miejsce schronienia.": "Check where the nearest shelter is.",
    "Przygotuj swoje otoczenie — Dom lub mieszkanie": "Prepare your surroundings — House or flat",
    "najbezpieczniejsze miejsce w domu": "the safest place at home",
    "Sprawdź, które miejsce w domu jest najbezpieczniejsze: z dala od okien, przy ścianach nośnych, w centralnych pomieszczeniach.": "Check which place at home is the safest: away from windows, by load-bearing walls, in central rooms.",
    "Dom lub mieszkanie": "House or flat",
    "Przygotuj się na przerwy w dostawach wody, prądu, gazu i na brak dostępu do telefonu i internetu.": "Be ready for interruptions in water, electricity and gas supply and for no access to phone and internet.",
    "Przygotuj przedmioty do uszczelniania i zabezpieczania okien i drzwi, np. koce, ręczniki, taśmy.": "Have items ready for sealing and securing windows and doors, e.g. blankets, towels, tape.",
    "Usuń z korytarzy i klatek schodowych niepotrzebne przedmioty.": "Remove unnecessary items from corridors and staircases.",
    "Oznacz w widoczny sposób, np. kolorowymi taśmami, miejsca odcięcia gazu, prądu i wody. Przećwicz z najbliższymi ich wyłączanie.": "Clearly mark, e.g. with coloured tape, where to shut off gas, electricity and water. Practise switching them off with your household.",
    "Zamontuj czujki dymu, czadu i gazu. Regularnie sprawdzaj ich stan techniczny. Dokładnie sprawdź umiejscowienie czujek.": "Install smoke, carbon monoxide and gas detectors. Check them regularly. Check carefully where the detectors are placed.",
    "Wyposaż dom w gaśnicę i koc gaśniczy.": "Equip your home with a fire extinguisher and a fire blanket.",
    "Pamiętaj o regularnych przeglądach instalacji: kominowej, wentylacyjnej, gazowej i elektrycznej oraz o ubezpieczeniu domu/mieszkania.": "Remember regular inspections of the chimney, ventilation, gas and electrical installations, and home insurance.",
    "Zapasy domowe na minimum 3 dni": "Household supplies for at least 3 days",
    "Jedzenie i picie: minimum 3 litry wody na osobę na dobę, żywność gotowa do spożycia.": "Food and drink: at least 3 litres of water per person per day, ready-to-eat food.",
    "Apteczka: leki przyjmowane na stałe, przeciwbólowe, przeciwzapalne, przeciwwymiotne, przeciwbiegunkowe, gaza, bandaże, opatrunki na oparzenia, rękawiczki jednorazowe, środki antyseptyczne, opaska do tamowania krwotoków, termometr i nożyczki, maseczki FFP3, folia termiczna.": "First-aid kit: regular medication, painkillers, anti-inflammatories, anti-nausea and anti-diarrhoea medicines, gauze, bandages, burn dressings, disposable gloves, antiseptics, a tourniquet, a thermometer and scissors, FFP3 masks, a thermal blanket.",
    "Środki czystości i higieny osobistej: papier toaletowy, chusteczki nawilżane, podpaski, pieluchy, środki dezynfekujące, worki na śmieci, wiadro z pokrywą.": "Cleaning and personal hygiene products: toilet paper, wet wipes, sanitary pads, nappies, disinfectants, bin bags, a bucket with a lid.",
    "Oświetlenie i łączność: latarka i radio na baterie lub na korbkę, naładowany telefon, ładowarka, naładowany powerbank, pasujące kable i baterie, świeczki do użytku domowego, zapalniczka.": "Light and communication: a torch and a battery or wind-up radio, a charged phone, a charger, a charged power bank, matching cables and batteries, household candles, a lighter.",
    "Koce, śpiwory i ciepła odzież.": "Blankets, sleeping bags and warm clothing.",
    "Gotówka w różnych nominałach.": "Cash in various denominations.",
    "Narzędzia i sprzęt: taśmy, folie, zestawy do uszczelniania.": "Tools and equipment: tape, plastic sheeting, sealing kits.",
    "Alternatywne źródło ogrzewania, które nie działa na prąd.": "An alternative source of heating that doesn't run on electricity.",
    "Plecak ewakuacyjny": "Emergency backpack",
    "Przygotuj podręczny zestaw najbardziej potrzebnych rzeczy. Skorzystaj z naszej listy i dopasuj ją do swoich potrzeb. Plecak ewakuacyjny powinien mieć każdy domownik, nawet dzieci.": "Prepare a handy kit of the most necessary things. Use our list and adapt it to your needs. Every member of the household, even children, should have an emergency backpack.",
    "Woda butelkowana. Filtry lub tabletki do uzdatniania wody.": "Bottled water. Water filters or purification tablets.",
    "Apteczka i leki osobiste, środki higieniczne i do dezynfekcji.": "A first-aid kit and personal medication, hygiene and disinfection products.",
    "Dokumenty, kopie na pendrivie i gotówka w różnych nominałach.": "Documents, copies on a USB stick and cash in various denominations.",
    "Latarka i radio na baterie lub na korbkę, naładowany telefon i powerbank, ładowarka, pasujące kable i zapasowe baterie.": "A torch and a battery or wind-up radio, a charged phone and power bank, a charger, matching cables and spare batteries.",
    "Scyzoryk lub multitool, zapalniczka, worki na śmieci, mapy drukowane.": "A penknife or multitool, a lighter, bin bags, printed maps.",
    "Żywność wysokoodżywcza gotowa do spożycia (batony energetyczne, suszone owoce, bakalie itp.).": "High-energy ready-to-eat food (energy bars, dried fruit, nuts, etc.).",
    "Ważna rzecz osobista, np. zdjęcie, pamiątka rodzinna.": "An important personal item, e.g. a photo, a family keepsake.",
    "Ubranie dopasowane do pory roku, odzież przeciwdeszczowa, śpiwór, karimata, folia termiczna.": "Clothing suited to the season, rainwear, a sleeping bag, a sleeping mat, a thermal blanket.",
    "Alternatywna łączność (np. walkie-talkie).": "Alternative communication (e.g. walkie-talkie).",
    "Plan na kryzys": "Crisis plan",
    "Opracuj rodzinny plan na wypadek kryzysu.": "Make a family plan for a crisis.",
    "Ustal dane kontaktowe oraz miejsca i terminy spotkań – w okolicy i poza miejscowością zamieszkania. To ważne na wypadek rozdzielenia i braku łączności.": "Agree on contact details and meeting places and times – nearby and outside your town. This matters in case you get separated and have no connection.",
    "Regularnie go aktualizuj i ćwicz z domownikami.": "Update it regularly and practise it with your household.",
    "Sprawdź, gdzie są wyjścia ewakuacyjne, miejsca zbiórki, gaśnice, defibrylatory (AED) i apteczki.": "Check where the emergency exits, assembly points, fire extinguishers, defibrillators (AED) and first-aid kits are.",
    "Zgłaszaj natychmiast nieprawidłowości, które zauważysz, np. uszkodzoną instalację elektryczną, zablokowane drogi ewakuacyjne, niesprawne windy.": "Immediately report any problems you notice, e.g. damaged wiring, blocked escape routes, broken lifts.",
    "Przećwiczcie ze współpracownikami plan awaryjny i ewakuację. Upewnij się, że wiesz, jak rozpoznawać, zapobiegać, alarmować i reagować na zagrożenia w Twojej pracy.": "Practise the emergency plan and evacuation with your colleagues. Make sure you know how to recognise, prevent, raise the alarm about and respond to hazards at your work.",
    "Szkoła": "School",
    "Jeżeli uczysz się w szkole, bierz udział w próbnych alarmach. Informuj nauczycieli o podejrzanych zachowaniach lub przedmiotach.": "If you are at school, take part in alarm drills. Tell your teachers about suspicious behaviour or objects.",
    "Jeżeli Twoje dziecko jest uczniem, zapisz kontakt do osoby wyznaczonej przez szkołę w sprawie odbioru dzieci w sytuacji zagrożenia.": "If your child goes to school, note the contact of the person the school has designated for collecting children in an emergency.",
    "Osoby potrzebujące szczególnej pomocy": "People who need special help",
    "W sytuacjach kryzysowych pomóż osobom starszym, chorym czy z niepełnosprawnościami. Nie wszyscy mogą być świadomi nadchodzącego zagrożenia, dlatego przekaż im najważniejsze informacje i wyjaśnij, co trzeba zrobić.": "In crisis situations help older, ill or disabled people. Not everyone may be aware of an approaching threat, so pass on the most important information and explain what needs to be done.",
    "Ustal z osobą, którą wspierasz, sposób działania w sytuacji kryzysowej.": "Agree with the person you support on how to act in a crisis.",
    "Pomóż w przygotowaniach, np. spakuj plecak ewakuacyjny dla osoby wspieranej, upewnij się, że ma zapas niezbędnych leków i baterii do urządzeń wspomagających (aparat słuchowy, sensor do pomiaru cukru itp.).": "Help with preparations, e.g. pack an emergency backpack for the person you support, make sure they have a supply of essential medicines and batteries for assistive devices (hearing aid, glucose sensor, etc.).",
    "W razie nagłego zagrożenia poinformuj służby ratownicze o osobie, która wymaga szczególnej pomocy podczas ewakuacji.": "In a sudden emergency, tell the emergency services about a person who needs special help during evacuation.",
    "Cytaty bez zmian treści. Grota nie jest publikacją urzędową.": "Quotes unchanged in meaning (translated). Grota is not an official publication.",
    "Uczelnia": "University",
    "Szpital / przychodnia": "Hospital / clinic",
    "Urząd": "Public office",
    "Policja / straż / wojsko": "Police / fire service / military",
    "Kultura (dom kultury, kino, teatr, biblioteka)": "Culture (community centre, cinema, theatre, library)",
    "Hala sportowa / basen": "Sports hall / swimming pool",
    "Kościół / świątynia": "Church / place of worship",
    "Centrum handlowe": "Shopping centre",
    "Sklep / centrum handlowe": "Shop / shopping centre",
    "Biurowiec / usługi": "Office building / services",
    "Hotel / akademik": "Hotel / student hall",
    "Dworzec / stacja / metro": "Station / metro",
    "Parking podziemny": "Underground car park",
    "Garaże / parking wielopoziomowy": "Garages / multi-storey car park",
    "Zakład / magazyn": "Factory / warehouse",
    "Blok mieszkalny": "Block of flats",
    "Dom jednorodzinny": "Detached house",
    "Budynek gospodarczy / rolniczy": "Outbuilding / farm building",
    "Budynek publiczny": "Public building",
    "Budynek (rodzaj nieoznaczony w mapie)": "Building (type not marked on the map)",
    "miasto": "town",
    "wieś": "village",
    "osada / przysiółek": "hamlet",
    "dzielnica / osiedle": "district / estate",
    "Parkingi podziemne i garaże": "Underground car parks and garages",
    "Centra handlowe": "Shopping centres",
    "Dworce, stacje, metro": "Stations, metro",
    "Bloki mieszkalne": "Blocks of flats",
    "Domy i zabudowa wiejska": "Houses and rural buildings",
    "Szkoły, przedszkola, uczelnie": "Schools, kindergartens, universities",
    "Szpitale i przychodnie": "Hospitals and clinics",
    "Urzędy i służby": "Public offices and services",
    "Biura, sklepy, hotele, zakłady": "Offices, shops, hotels, factories",
    "Kultura, sport, świątynie": "Culture, sport, places of worship",
    "Rodzaj nieznany": "Unknown type",
    "Sygnały alarmowe": "Alarm signals",
    "Przygotuj swoje otoczenie": "Prepare your surroundings",
    "W godzinach": "During hours",
    "Sprawdzone": "Verified",
    "Do sprawdzenia": "To check",
    "Wątpliwe": "Doubtful",
    "Chwilowo brak pozycji GPS — nagrywanie trwa.": "No GPS position for the moment — recording continues.",
    "Brak zgody na lokalizację. Włącz ją w Ustawieniach iPhone'a: Ustawienia → Strażnik → Lokalizacja → „Podczas używania aplikacji”. Możesz też wybrać, gdzie jesteś, poniżej.": "No location permission. Turn it on in the iPhone Settings: Settings → Strażnik → Location → “While Using the App”. You can also choose where you are below.",
    "Telefon nie ustalił pozycji. Sprawdź, czy usługi lokalizacji są włączone (Ustawienia → Prywatność i ochrona → Usługi lokalizacji), albo wybierz, gdzie jesteś, poniżej.": "The phone couldn't find your position. Check that Location Services are on (Settings → Privacy & Security → Location Services), or choose where you are below.",
    "Ustalanie pozycji trwało zbyt długo. Spróbuj jeszcze raz albo wskaż miejsce na mapie.": "Finding your position took too long. Try again or pick the place on the map.",
    "Brak zgody na lokalizację. Włącz ją w ustawieniach telefonu: Aplikacje → Strażnik → Uprawnienia → Lokalizacja. Możesz też wybrać, gdzie jesteś, poniżej.": "No location permission. Turn it on in your phone settings: Apps → Strażnik → Permissions → Location. You can also choose where you are below.",
    "Telefon nie ustalił pozycji. Sprawdź, czy lokalizacja jest włączona (szybkie ustawienia u góry ekranu), albo wybierz, gdzie jesteś, poniżej.": "The phone couldn't find your position. Check that location is on (quick settings at the top of the screen), or choose where you are below.",
    "Brak zgody na lokalizację. Kliknij ikonę kłódki przy adresie strony i zezwól na lokalizację. Na komputerze z Windows sprawdź też: Ustawienia → Prywatność i zabezpieczenia → Lokalizacja (włączona, także dla przeglądarki).": "No location permission. Click the padlock icon next to the page address and allow location. On a Windows computer also check: Settings → Privacy & security → Location (on, also for the browser).",
    "Urządzenie nie ustaliło pozycji. Komputer bez GPS korzysta z sieci Wi-Fi — sprawdź, czy lokalizacja jest włączona w systemie.": "The device couldn't find its position. A computer without GPS uses Wi-Fi networks — check that location is enabled in the system.",
    "adres z bazy GUGiK": "address from the GUGiK database",
    "środek miejscowości (spis OpenStreetMap)": "town centre (OpenStreetMap list)",
    "punkt wskazany na mapie": "point picked on the map",
    "miejsce wskazane na mapie": "place picked on the map",
    "Nie udało się wczytać punktów schronienia. Zasady i listy „Przygotuj się” działają bez nich.": "Couldn't load the shelter points. The rules and the “Get prepared” lists work without them.",
    "Najpierw ustal pozycję albo wybierz zapisane miejsce.": "First find your position or choose a saved place.",
    "Dla tego obszaru nie ma jeszcze mapy do pobrania.": "There's no map to download for this area yet.",
    "Lokalizacja działa tylko na stronie https albo localhost.": "Location only works on an https page or localhost.",
    "Ta przeglądarka nie udostępnia lokalizacji.": "This browser doesn't provide location.",
    "Pokaż punkty": "Show points",
    "Filtr włączony — lista pokazuje tylko zaznaczone punkty. Odległości przy przyciskach liczone są od tego miejsca.": "Filter on — the list shows only the selected points. The distances on the buttons are measured from this place.",
    "Prowadź do punktów": "Guide to points",
    "Filtr włączony — Grota prowadzi tylko do zaznaczonych punktów. Odległości przy przyciskach pokazują, ile dzieli Cię od najbliższego punktu każdego rodzaju.": "Filter on — Grota guides you only to the selected points. The distances on the buttons show how far the nearest point of each type is.",
    "Grota prowadzi tylko do punktów o sprawdzonym położeniu. Punkty wątpliwe pomija i pisze o nich pod propozycją.": "Grota guides you only to points with a verified location. It skips doubtful points and mentions them below the suggestion.",
    "Wpisz, gdzie jesteś": "Enter where you are",
    "Nowy adres": "New address",
    "Adres miejsca": "Address of the place",
    "Adres albo miejscowość miejsca spotkania": "Address or town of the meeting place",
    "albo wpisz adres / miejscowość": "or enter an address / town",
    "GPS nie działa? Wpisz adres albo miejscowość": "GPS not working? Enter an address or town",
    "Wokół miejsca": "Around a place",
    "Cała Polska": "All of Poland",
    "Zdjęcie z góry, ok. 140 m szerokości · punkt w środku · ortofotomapa GUGiK": "Aerial photo, about 140 m wide · point in the centre · GUGiK orthophoto map",
    "Zdjęcie z góry · punkt w środku · ortofotomapa GUGiK": "Aerial photo · point in the centre · GUGiK orthophoto map",
    "Komenda Główna PSP, dane.gov.pl, CC BY 4.0": "National Headquarters of the State Fire Service (KG PSP), dane.gov.pl, CC BY 4.0",
    "nr publikacji 1/2025": "publication no. 1/2025",
    "Komenda Główna PSP, „Punkty schronienia w Polsce”, dane.gov.pl, CC BY 4.0": "National Headquarters of the State Fire Service (KG PSP), “Punkty schronienia w Polsce” (Shelter points in Poland), dane.gov.pl, CC BY 4.0",
    "{x} m": "{x} m",
    "{x} km": "{x} km",
    "{x} MB": "{x} MB",
    "{x} GB": "{x} GB",
    "{m} min": "{m} min",
    "Strażnik": "Strażnik",
    "Wróć do Strażnika": "Back to Strażnik",
    "Mapa": "Map",
    "Miejsca": "Places",
    "TERAZ": "NOW",
    "Przygotuj": "Prepare",
    "Zasady": "Rules",
    "Schronienie teraz": "Shelter now",
    "Moje miejsca": "My places",
    "gdzie się schronić": "where to take shelter",
    "prototyp · cała Polska": "prototype · all of Poland",
    "Jasna / ciemna mapa": "Light / dark map",
    "Jasna albo ciemna mapa": "Light or dark map",
  };
})(typeof window !== "undefined" ? window : globalThis);
