/* GROTA — українська. Ключ = польський текст точно як у коді (див. jezyk.js).
   Множина: "one|few|many" (польською) → [1, 2–4, 5+] за українськими правилами.
   Адреси й назви місць лишаються польською; цитати з «Poradnik bezpieczeństwa» (Порадника з безпеки,
   виданого урядом Польщі) — наш переклад, про що застосунок пише під кожною цитатою. */
(function (global) {
  "use strict";
  (global.GROTA_SLOWNIK = global.GROTA_SLOWNIK || {}).uk = {
    "czas: sprawdź w Google Maps": "час: перевірте в Google Maps",
    "ok. {m} min (szacunek)": "бл. {m} хв (оцінка)",
    "trasy i punkty: {osm} · schronienia: KG PSP, CC BY 4.0": "маршрути й пункти: {osm} · укриття: KG PSP, CC BY 4.0",
    "Punkty, Twoje miejsca i nagrane trasy działają. Wyszukiwarka adresów, wstępne trasy i zdjęcia z góry wrócą z siecią.": "Пункти, ваші місця й записані маршрути працюють. Пошук адрес, попередні маршрути й знімки згори повернуться разом з мережею.",
    "Bez internetu · mapa uproszczona": "Без інтернету · спрощена мапа",
    "Odśwież": "Оновити",
    "Test bez internetu · mapa z pamięci telefonu": "Тест без інтернету · мапа з пам'яті телефону",
    "Bez internetu · mapa z pamięci telefonu": "Без інтернету · мапа з пам'яті телефону",
    "Zakończ test": "Завершити тест",
    "Przygotowuję mapę… {p}%": "Готую мапу… {p}%",
    "Wczytuję punkty schronienia z całej Polski…": "Завантажую пункти укриття з усієї Польщі…",
    "Wczytuję punkty… {p}%": "Завантажую пункти… {p}%",
    "{s} s": "{s} с",
    "{m} min {s} s": "{m} хв {s} с",
    "Nagrywam trasę": "Записую маршрут",
    "czekam na GPS…": "чекаю на GPS…",
    "do celu {d}": "до мети {d}",
    "Słaby sygnał GPS — punkty pomijam, dopóki dokładność nie będzie lepsza niż {m} m.": "Слабкий сигнал GPS — пропускаю точки, доки точність не стане кращою за {m} м.",
    "Zakończ i zapisz": "Завершити й зберегти",
    "Anuluj": "Скасувати",
    "Nagrywanie trasy wymaga lokalizacji (strona https albo localhost).": "Для запису маршруту потрібна геолокація (сторінка https або localhost).",
    "Nagrywanie trasy z „{n}” do: {a}.": "Запис маршруту з «{n}» до: {a}.",
    "Idź tak, jak szedłbyś w czasie alarmu — najkrótszą bezpieczną drogą, którą znasz. Nagrywanie działa tylko przy włączonym ekranie.": "Ідіть так, як ішли б під час тривоги, — найкоротшим безпечним шляхом, який знаєте. Запис працює лише з увімкненим екраном.",
    "Zacząć?": "Почати?",
    "Nagrano za mało drogi, żeby zapisać trasę. Przerwać nagrywanie?": "Записано замало шляху, щоб зберегти маршрут. Зупинити запис?",
    "początek jest {d} od miejsca „{n}”": "початок за {d} від місця «{n}»",
    "koniec jest {d} od schronienia": "кінець за {d} від укриття",
    "Uwaga: {w}. Zapisać trasę mimo to?": "Увага: {w}. Усе одно зберегти маршрут?",
    "Przerwać nagrywanie bez zapisu?": "Зупинити запис без збереження?",
    "Trwa nagrywanie tej trasy — pasek nagrywania jest na mapie.": "Цей маршрут записується — панель запису на мапі.",
    "Twoja trasa: {d} · {t}": "Ваш маршрут: {d} · {t}",
    "nagrana {data} · {tryb} · w alarmie Grota pokaże ją zamiast wyliczonej": "записаний {data} · {tryb} · під час тривоги Grota покаже його замість обчисленого",
    "Przejdź tę drogę na próbę i nagraj ją. W alarmie Grota pokaże Twoją sprawdzoną trasę zamiast wyliczonej — także skróty, których nie ma w mapach.": "Пройдіть цей шлях на пробу й запишіть його. Під час тривоги Grota покаже ваш перевірений маршрут замість обчисленого — разом зі скороченнями, яких немає на мапах.",
    "Pokaż na mapie": "Показати на мапі",
    "Nagraj ponownie": "Записати знову",
    "Nagraj swoją trasę": "Записати свій маршрут",
    "Usuń nagraną trasę": "Видалити записаний маршрут",
    "Czas do zagrożenia to wyliczenie z zagrożeń widocznych w Strażniku. Alert RCB może dotyczyć czegoś, czego Strażnik nie widzi — wtedy realnie jest mniej czasu. Gdy przyszedł alert RCB albo słychać syreny, nie licz minut: działaj według komunikatu.": "Час до загрози обчислено із загроз, які бачить Strażnik. Урядове попередження RCB може стосуватися того, чого Strażnik не бачить, — тоді часу насправді менше. Якщо надійшло попередження RCB або чути сирени, не рахуйте хвилин: дійте за повідомленням.",
    "Cel": "Мета",
    "Twoja nagrana trasa {d} · {t}": "Ваш записаний маршрут {d} · {t}",
    "przećwiczona {data} ({tryb}) · pomarańczowa linia na mapie": "відпрацьований {data} ({tryb}) · помаранчева лінія на мапі",
    "Wyznaczam wstępną trasę…": "Прокладаю попередній маршрут…",
    "Trasa {d} · ok. {m} min": "Маршрут {d} · бл. {m} хв",
    "policzona z mapy w telefonie — bez internetu, więc przybliżona": "обчислений з мапи в телефоні — без інтернету, тому приблизний",
    "Bez internetu nie da się wyznaczyć trasy po ulicach, a w pobranej mapie nie ma tu połączenia. Na mapie kierunek i odległość w linii prostej.": "Без інтернету маршрут вулицями не прокласти, а в завантаженій мапі тут немає сполучення. На мапі — напрямок і відстань по прямій.",
    "Nie udało się wyznaczyć trasy (brak sieci?). Na mapie linia prosta — trasę pokaże Google Maps.": "Не вдалося прокласти маршрут (немає мережі?). На мапі пряма лінія — маршрут покаже Google Maps.",
    "po drogach i ścieżkach z mapy, bez korków i utrudnień · linia przerywana: kierunek w linii prostej · © OpenStreetMap, serwer tras FOSSGIS": "дорогами й стежками з мапи, без заторів і перешкод · пунктир: напрямок по прямій · © OpenStreetMap, сервер маршрутів FOSSGIS",
    "Tu jesteś": "Ви тут",
    "Pozycja jest bardzo przybliżona ({acc}). Wskaż swoje miejsce na mapie albo wybierz, gdzie jesteś.": "Позиція дуже приблизна ({acc}). Вкажіть своє місце на мапі або виберіть, де ви.",
    "Pozycja jest bardzo przybliżona ({acc}). Na komputerze bez GPS i Wi-Fi przeglądarka zgaduje miejsce z adresu internetowego — często wychodzi np. Warszawa. Wskaż swoje miejsce na mapie albo wybierz, gdzie jesteś.": "Позиція дуже приблизна ({acc}). На комп'ютері без GPS і Wi-Fi браузер вгадує місце за інтернет-адресою — часто виходить, наприклад, Варшава. Вкажіть своє місце на мапі або виберіть, де ви.",
    "Nowe położenie miejsca „{n}” jest daleko od zapisanych tu schronień (najbliższe {d} stąd).": "Нове розташування місця «{n}» далеко від збережених тут укриттів (найближче за {d}).",
    "To schronienie zostanie usunięte z tego miejsca": "Це укриття буде видалено з цього місця",
    "Zapisane schronienia ({n}) zostaną usunięte z tego miejsca": "Збережені укриття ({n}) буде видалено з цього місця",
    ", razem z nagraną trasą": " разом із записаним маршрутом",
    ", razem z nagranymi trasami ({n})": " разом із записаними маршрутами ({n})",
    "Punkty zostają na mapie — do nowego adresu wybierzesz schronienia na nowo.": "Пункти лишаються на мапі — для нової адреси ви оберете укриття заново.",
    "Zmienić położenie?": "Змінити розташування?",
    "„{tekst}”": "«{tekst}»",
    "„Poradnik bezpieczeństwa”, s. {s}": "«Poradnik bezpieczeństwa» (Порадник з безпеки), с. {s}",
    "tłumaczenie nasze, oryginał po polsku": "наш переклад, оригінал польською",
    "{n}: moje miejsce w budynku": "{n}: моє місце в будівлі",
    "Sprawdzone przez Ciebie.": "Перевірено вами.",
    "Jeszcze nie sprawdzone na miejscu.": "Ще не перевірено на місці.",
    "Zwiń": "Згорнути",
    "Otwórz": "Відкрити",
    "Zapisz jako schronienie dla:": "Зберегти як укриття для:",
    "To miejsce ma już 3 schronienia": "Це місце вже має 3 укриття",
    "Zdjęcie z góry okolicy punktu": "Знімок згори околиць пункту",
    "Zdjęcie z góry niedostępne (brak sieci albo usługa GUGiK nie odpowiada).": "Знімок згори недоступний (немає мережі або сервіс GUGiK не відповідає).",
    "gm. {g}": "гміна {g}",
    "Jak wejść — godziny, kto otwiera, kontakt do zarządcy (Twoja notatka)": "Як увійти — години, хто відчиняє, контакт управителя (ваша нотатка)",
    "np. administrator osiedla, tel. …; otwarte 7–15": "напр. адміністратор житлового комплексу, тел. …; відчинено 7–15",
    "{d} od miejsca": "{d} від місця",
    "{d} od Ciebie": "{d} від вас",
    "Przećwicz trasę": "Відпрацювати маршрут",
    "Prowadź": "Вести",
    "Ustalam pozycję…": "Визначаю позицію…",
    "Narysuj trasę tutaj, na mapie Groty": "Накреслити маршрут тут, на мапі Grota",
    "„Prowadź\" otwiera nawigację w telefonie. Bez internetu albo bez tej aplikacji nawigacja nie ruszy — wtedy ten guzik rysuje trasę orientacyjną na mapie Groty, z tego, co telefon ma u siebie.": "«Вести» відкриває навігацію в телефоні. Без інтернету або без цього застосунку навігація не запуститься — тоді ця кнопка креслить орієнтовний маршрут на мапі Grota з того, що є в телефоні.",
    "Skąd biorą się przesunięte punkty?": "Звідки беруться зміщені пункти?",
    "Adresy i współrzędne pochodzą z publicznego zbioru Komendy Głównej PSP — tego samego, z którego korzystają inne aplikacje i serwisy. {ile} z {wszystkie} punktów ma oznaczone wątpliwe położenie: najczęściej szpilka stoi obok budynku — na podwórku, parkingu albo trawniku — rzadziej wskazuje miejsce poza miejscowością z adresu albo w innej gminie. <b>To błąd w danych źródłowych</b> i w tym, jak są dalej przetwarzane — nie w Grocie.": "Адреси й координати походять з відкритого набору даних Головної комендатури Державної пожежної служби (PSP) — того самого, яким користуються інші застосунки й сервіси. {ile} з {wszystkie} пунктів мають позначене сумнівне розташування: найчастіше шпилька стоїть поруч із будівлею — у дворі, на парковці чи газоні, — рідше вказує місце поза населеним пунктом з адреси або в іншій гміні. <b>Це помилка у вихідних даних</b> і в тому, як їх далі обробляють, — не в Grota.",
    "Grota takich punktów nie przesuwa po cichu ani nie ukrywa: oznacza je obwódką, nie poleca jako pierwszych i pisze, co stoi najbliżej szpilki. Szukaj w terenie tego budynku, nie samej szpilki.": "Grota не пересуває таких пунктів потай і не приховує їх: позначає обвідкою, не пропонує першими й пише, що стоїть найближче до шпильки. На місці шукайте цю будівлю, а не саму шпильку.",
    "{n} pkt": "{n} пкт",
    "Pokaż wszystkie": "Показати всі",
    "Rodzaj budynku (wg OpenStreetMap)": "Тип будівлі (за OpenStreetMap)",
    "Każdy przycisk włącza lub wyłącza swoją grupę. „Pokaż wszystkie” zaznacza wszystko, a naciśnięte ponownie — odznacza.": "Кожна кнопка вмикає або вимикає свою групу. «Показати всі» позначає все, а натиснута ще раз — знімає позначки.",
    "Widać wszystkie punkty.": "Видно всі пункти.",
    "Widać {n} z {wszystkie} punktów.": "Видно {n} з {wszystkie} пунктів.",
    "Nic nie jest zaznaczone — mapa nie pokazuje żadnego punktu.": "Нічого не позначено — мапа не показує жодного пункту.",
    "Filtr dotyczy tylko mapy — „Teraz” zawsze szuka wśród wszystkich sprawdzonych punktów.": "Фільтр стосується лише мапи — «Зараз» завжди шукає серед усіх перевірених пунктів.",
    "Wybrany punkt": "Вибраний пункт",
    "Zamknij": "Закрити",
    "Zamknij kartę punktu": "Закрити картку пункту",
    "Czemu nie ma tu „schronów”?": "Чому тут немає «сховищ»?",
    "Zamknij informację": "Закрити інформацію",
    "Publiczne dane PSP nie rozróżniają schronu, ukrycia i miejsca doraźnego schronienia — pełna ewidencja (CEOZO) z mocy ustawy nie jest informacją publiczną.": "Відкриті дані PSP не розрізняють сховище, укриття й місце тимчасового укриття — повний реєстр (CEOZO) за законом не є публічною інформацією.",
    "Wyjaśnienie i źródła": "Пояснення й джерела",
    "Filtry i widok": "Фільтри й вигляд",
    "Środek transportu": "Спосіб пересування",
    "Źródło: {zrodlo}; dane z {data}. Dane nie zawierają liczby miejsc ani rodzaju obiektu (schron / ukrycie / miejsce doraźne).": "Джерело: {zrodlo}; дані від {data}. Дані не містять кількості місць і типу об'єкта (сховище / укриття / тимчасове місце).",
    "Dotknij punktu na mapie — jego karta pojawi się tutaj.": "Торкніться пункту на мапі — його картка з'явиться тут.",
    "Wczytuję dane…": "Завантажую дані…",
    "Zapisano": "Збережено",
    "schronienia: {n}/3": "укриття: {n}/3",
    "nagrane trasy: {n}": "записані маршрути: {n}",
    "wskazane na mapie": "вказане на мапі",
    "Położenie": "Розташування",
    "(przybliżone — popraw w „Edytuj”)": "(приблизне — виправте в «Редагувати»)",
    "Moje miejsce w budynku": "Моє місце в будівлі",
    "· sprawdzone": "· перевірено",
    "· jeszcze nie sprawdzone": "· ще не перевірено",
    "nie zapisano": "не збережено",
    "Edytuj dane miejsca": "Редагувати дані місця",
    "Moje miejsca schronienia ({n}/3)": "Мої укриття ({n}/3)",
    "Usuń z listy": "Видалити зі списку",
    "Wybierz do trzech poniżej i przećwicz drogę — poradnik zaleca iść „ustaloną wcześniej drogą” (s. 34).": "Виберіть до трьох нижче й відпрацюйте шлях — порадник радить іти «заздалегідь визначеним шляхом» (с. 34).",
    "Wybierz miejsca schronienia": "Виберіть укриття",
    "Brak punktów spełniających filtr w pobliżu. Zaznacz więcej rodzajów powyżej.": "Поблизу немає пунктів, що відповідають фільтру. Позначте більше типів вище.",
    "Nazwa": "Назва",
    "Położenie przybliżone („{a}”) — wpisz dokładny adres albo wskaż budynek na mapie.": "Приблизне розташування («{a}») — введіть точну адресу або вкажіть будівлю на мапі.",
    "Położenie przybliżone — wpisz dokładny adres albo wskaż budynek na mapie.": "Приблизне розташування — введіть точну адресу або вкажіть будівлю на мапі.",
    "Moja pozycja": "Моя позиція",
    "Wskaż na mapie": "Вказати на мапі",
    "Kliknij na mapie nowe położenie miejsca „{n}”.": "Торкніться на мапі нового розташування місця «{n}».",
    "Rodzaj miejsca": "Тип місця",
    "Moje miejsce w tym budynku": "Моє місце в цій будівлі",
    "Twoja notatka, np. „korytarz na parterze, bez okien”": "Ваша нотатка, напр. «коридор на першому поверсі, без вікон»",
    "Sprawdziłem to miejsce na miejscu": "Я перевірив це місце на місці",
    "Środek transportu z tego miejsca": "Спосіб пересування з цього місця",
    "Gotowe": "Готово",
    "Przeciągnij, aby zmienić kolejność": "Перетягніть, щоб змінити порядок",
    "Zmień kolejność: {n} (strzałki w górę i w dół)": "Змінити порядок: {n} (стрілки вгору й униз)",
    "Edytuj": "Редагувати",
    "Edytuj {n}": "Редагувати {n}",
    "Usuń miejsce": "Видалити місце",
    "Usuń miejsce {n}": "Видалити місце {n}",
    "Moje stałe miejsca": "Мої постійні місця",
    "Miejsca są zapisywane tylko na tym urządzeniu. Dotknij miejsca, aby zobaczyć szczegóły.": "Місця зберігаються лише на цьому пристрої. Торкніться місця, щоб побачити подробиці.",
    "Kolejność zmienisz, przeciągając kafel za uchwyt ⋮⋮.": "Порядок зміните, перетягнувши плитку за ручку ⋮⋮.",
    "Nie masz jeszcze zapisanych miejsc — dodaj dom, pracę albo szkołę dziecka poniżej.": "У вас ще немає збережених місць — додайте дім, роботу або школу дитини нижче.",
    "Dodaj miejsce": "Додати місце",
    "Wybierz rodzaj. Pełny kolor — takie miejsce już masz.": "Виберіть тип. Повний колір — таке місце у вас уже є.",
    "Nowe miejsce: {rodzaj}": "Нове місце: {rodzaj}",
    "albo": "або",
    "Kliknij na mapie położenie miejsca „{n}”.": "Торкніться на мапі розташування місця «{n}».",
    "Wybrane przez Ciebie miejsce schronienia": "Вибране вами укриття",
    "Najbliższe sprawdzone miejsce schronienia": "Найближче перевірене укриття",
    "ok. {m} min trasą": "бл. {m} хв маршрутом",
    "PROWADŹ ➜": "ВЕСТИ ➜",
    "Wybierz to miejsce: {a}": "Вибрати це місце: {a}",
    "wg OpenStreetMap": "за OpenStreetMap",
    "Jestem w:": "Я в:",
    "Pozycja z GPS": "Позиція з GPS",
    "Wpisz adres": "Ввести адресу",
    "Nic nie znalazłem. Spróbuj: „Miejscowość, ulica numer” albo samą miejscowość.": "Нічого не знайдено. Спробуйте: «Населений пункт, вулиця номер» або лише населений пункт.",
    "Brak połączenia z wyszukiwarką adresów. Pokazuję miejscowości zapisane w aplikacji — pozycja to środek miejscowości.": "Немає з'єднання з пошуком адрес. Показую населені пункти, збережені в застосунку, — позиція означає центр населеного пункту.",
    "Nie znalazłem tego adresu ani ulicy. Miejscowości o tej nazwie — to tylko środek miejscowości:": "Не знайдено цієї адреси чи вулиці. Населені пункти з цією назвою — це лише центр населеного пункту:",
    "Nie znalazłem tego adresu ani ulicy. Miejscowości o tej nazwie — to tylko środek miejscowości, po wyborze popraw położenie na mapie:": "Не знайдено цієї адреси чи вулиці. Населені пункти з цією назвою — це лише центр населеного пункту; після вибору виправте розташування на мапі:",
    "Dokładnego adresu nie ma w bazie adresów (np. numer mieszkania albo litera). Wyniki są przybliżone.": "Точної адреси немає в базі адрес (напр. номер квартири чи літера). Результати приблизні.",
    "Dokładnego adresu nie ma w bazie adresów (np. numer mieszkania albo litera). Wyniki są przybliżone — po wyborze popraw położenie na mapie.": "Точної адреси немає в базі адрес (напр. номер квартири чи літера). Результати приблизні — після вибору виправте розташування на мапі.",
    "np. Warszawa, Marszałkowska 100 · Zalesie Górne": "напр. Warszawa, Marszałkowska 100 · Zalesie Górne",
    "Szukam…": "Шукаю…",
    "Szukaj": "Шукати",
    "Szukam od:": "Шукаю від:",
    "Zakończ": "Завершити",
    "Poziom alarmu opiera się na źródłach pośrednich": "Рівень тривоги ґрунтується на непрямих джерелах",
    "Nie ma teraz oficjalnego alertu RCB ani obiektu w powietrzu nad Polską. Grota pokazuje mapę, odległości i kierunki, ale <b>nie wzywa do schronienia</b> — kieruj się komunikatami służb, a jeśli ich nie ma, potraktuj to jako sygnał do uważności, nie do biegu.": "Зараз немає офіційного попередження RCB чи об'єкта в повітрі над Польщею. Grota показує мапу, відстані й напрямки, але <b>не закликає йти в укриття</b> — керуйтеся повідомленнями служб, а якщо їх немає, сприймайте це як сигнал бути уважними, а не бігти.",
    "pieszo ok. {p} min · samochodem ok. {s} min": "пішки бл. {p} хв · автомобілем бл. {s} хв",
    "To wyliczenie Groty, <b>nieoficjalne</b> — nie zastępuje komunikatów służb. Kieruj się w pierwszej kolejności oficjalnymi komunikatami (Alert RCB, RSO, radio, polecenia służb). Jeśli ich nie ma, potraktuj to jako podpowiedź.": "Це обчислення Grota, <b>неофіційне</b> — воно не замінює повідомлень служб. Насамперед керуйтеся офіційними повідомленнями (Alert RCB, RSO, радіо, вказівки служб). Якщо їх немає, сприймайте це як підказку.",
    "Umówione miejsce": "Домовлене місце",
    "Schowaj": "Сховати",
    "Wskaż miejsce": "Вказати місце",
    "Jeśli umówiliście się z bliskimi na konkretne miejsce, wpisz je — Grota poprowadzi tam tak samo jak do schronienia i powie, czy zdążysz.": "Якщо ви домовилися з близькими про конкретне місце, введіть його — Grota поведе туди так само, як до укриття, і скаже, чи встигнете.",
    "To miejsce jest za daleko — {czasy}, a zagrożenie za {eta} min.": "Це місце задалеко — {czasy}, а загроза за {eta} хв.",
    "Pieszo nie zdążysz — ok. {p} min przy zagrożeniu za {eta} min. Samochodem ok. {s} min.": "Пішки не встигнете — бл. {p} хв, а загроза за {eta} хв. Автомобілем бл. {s} хв.",
    "To daleko — {czasy}. Sprawdź, czy zdążysz.": "Це далеко — {czasy}. Перевірте, чи встигнете.",
    "To miejsce jest poza pobraną mapą.": "Це місце поза завантаженою мапою.",
    "Zamknij ostrzeżenie": "Закрити попередження",
    "To miejsce jest <b>poza pobraną mapą</b> — bez internetu zobaczysz tam sam kierunek i odległość.": "Це місце <b>поза завантаженою мапою</b> — без інтернету ви побачите туди лише напрямок і відстань.",
    "Strażnik nie podaje teraz czasu do zagrożenia (sygnały są za stare albo kurs jest niepewny), więc Grota go nie zgaduje — porównaj sam z komunikatami służb.": "Strażnik зараз не подає часу до загрози (сигнали застарі або курс непевний), тож Grota його не вгадує — порівняйте самі з повідомленнями служб.",
    "Schowaj kroki": "Сховати кроки",
    "Co robić teraz": "Що робити зараз",
    "Usuń": "Видалити",
    "Ustal swoją pozycję, żeby poznać odległość.": "Визначте свою позицію, щоб дізнатися відстань.",
    "Bez internetu i bez połączenia w pobranej mapie — na mapie kierunek i odległość w linii prostej.": "Без інтернету й без сполучення в завантаженій мапі — на мапі напрямок і відстань по прямій.",
    "Nie udało się wyznaczyć trasy (brak sieci?). Na mapie linia prosta.": "Не вдалося прокласти маршрут (немає мережі?). На мапі пряма лінія.",
    "— z mapy w telefonie": "— з мапи в телефоні",
    "Pokaż trasę": "Показати маршрут",
    "{km} km wokół Twojej pozycji": "{km} км навколо вашої позиції",
    "{km} km wokół: {n}": "{km} км навколо: {n}",
    "{km} km wokół miejsca": "{km} км навколо місця",
    "województwo {w}": "{w} воєводство",
    "cała Polska": "уся Польща",
    "(mapa {m} + trasy {t})": "(мапа {m} + маршрути {t})",
    "pobierze {x}": "завантажить {x}",
    "zajmie w telefonie ok. {x}.": "займе в телефоні бл. {x}.",
    "To, co już masz w telefonie, nie pobierze się drugi raz.": "Те, що вже є в телефоні, вдруге не завантажиться.",
    "(sama mapa)": "(лише мапа)",
    "Sprawdzam, jakie mapy są do pobrania…": "Перевіряю, які мапи можна завантажити…",
    "Spróbuj ponownie": "Спробувати ще раз",
    "Wokół czego": "Навколо чого",
    "mojej pozycji": "моєї позиції",
    "mojej pozycji (najpierw ustal pozycję)": "моєї позиції (спершу визначте позицію)",
    "Dla tego miejsca nie ma jeszcze mapy do pobrania. Na razie dostępne: {lista}.": "Для цього місця ще немає мапи для завантаження. Поки доступні: {lista}.",
    "Ustalam…": "Визначаю…",
    "Ustal pozycję": "Визначити позицію",
    "Albo wybierz wyżej jedno z zapisanych miejsc.": "Або виберіть вище одне зі збережених місць.",
    "Województwo": "Воєводство",
    "— wybierz —": "— виберіть —",
    "Na razie do pobrania: {n} z {w} województw. Pozostałe dochodzą.": "Поки можна завантажити: {n} з {w} воєводств. Решта додаються.",
    "Pobieraj całą Polskę tylko przez wifi i tylko wtedy, gdy masz tyle wolnego miejsca w telefonie.": "Завантажуйте всю Польщу лише через Wi-Fi і лише тоді, коли маєте стільки вільного місця в телефоні.",
    "Na razie w paczkach: {lista}.": "Поки в пакетах: {lista}.",
    "Przerwane. To, co zdążyło się pobrać, zostaje w telefonie — następna próba dobierze tylko resztę.": "Перервано. Те, що встигло завантажитися, лишається в телефоні — наступна спроба дозавантажить лише решту.",
    "kafelek mapy|kafelki mapy|kafelków mapy": ["фрагмент мапи", "фрагменти мапи", "фрагментів мапи"],
    "obszaru|obszarów|obszarów": ["області", "областей", "областей"],
    "Pobrano {mb}: {kafelki} i dane do tras dla {obszary}.": "Завантажено {mb}: {kafelki} і дані для маршрутів для {obszary}.",
    "Pobrano {mb}: {kafelki}.": "Завантажено {mb}: {kafelki}.",
    "Wszystko było już w telefonie.": "Усе вже було в телефоні.",
    "oba motywy": "обидві теми",
    "jeden motyw": "одна тема",
    "brak": "немає",
    "Mapa offline": "Мапа офлайн",
    "Pobrane:": "Завантажено:",
    "element mapy|elementy mapy|elementów mapy": ["елемент мапи", "елементи мапи", "елементів мапи"],
    "styl mapy: {s}": "стиль мапи: {s}",
    "obszar|obszary|obszarów": ["область", "області", "областей"],
    "dane do tras: {n}": "дані для маршрутів: {n}",
    "bez danych do tras": "без даних для маршрутів",
    "Przy alarmie sieć bywa przeciążona. Mapa pobrana wcześniej działa bez internetu — punkty schronienia i odległości działają zawsze, offline dochodzą do nich ulice.": "Під час тривоги мережа буває перевантажена. Мапа, завантажена заздалегідь, працює без інтернету — пункти укриття й відстані працюють завжди, а офлайн до них додаються вулиці.",
    "<b>Mapa offline to też miejsce dla innych.</b> W czasie alarmu z Groty korzystają tysiące osób naraz, a serwer jest jeden. Każdy, kto ma mapę w telefonie, zwalnia łącze komuś, kto nie zdążył jej pobrać.": "<b>Мапа офлайн — це також місце для інших.</b> Під час тривоги Grota користуються тисячі людей одночасно, а сервер один. Кожен, хто має мапу в телефоні, звільняє канал для того, хто не встиг її завантажити.",
    "Co pobrać": "Що завантажити",
    "Mapa i trasy": "Мапа й маршрути",
    "Sama mapa": "Лише мапа",
    "<b>Mapa i trasy.</b> Bez internetu Grota poprowadzi Cię ulicami i chodnikami do schronienia albo do umówionego miejsca. To jedyny wariant, który działa poza miastem: sama mapa ma jakąś trzecią część ścieżek, więc bez danych do tras na wsi zwykle nie ma z czego policzyć drogi.": "<b>Мапа й маршрути.</b> Без інтернету Grota поведе вас вулицями й тротуарами до укриття або до домовленого місця. Це єдиний варіант, що працює поза містом: сама мапа має приблизно третину стежок, тож без даних для маршрутів у селі зазвичай немає з чого обчислити шлях.",
    "<b>Sama mapa — mniejsza paczka.</b> Zobaczysz mapę, punkty schronienia i odległości, ale bez internetu Grota <b>nie wyznaczy trasy</b> — pokaże kierunek w linii prostej i budynki po drodze. W mieście to zwykle wystarcza, na wsi bywa za mało.": "<b>Лише мапа — менший пакет.</b> Ви побачите мапу, пункти укриття й відстані, але без інтернету Grota <b>не прокладе маршруту</b> — покаже напрямок по прямій і будівлі дорогою. У місті цього зазвичай досить, у селі буває замало.",
    "Przerywam…": "Перериваю…",
    "Sprawdzam, co jest do pobrania…": "Перевіряю, що потрібно завантажити…",
    "Pobieram wygląd mapy (kolory, ikony, napisy)…": "Завантажую вигляд мапи (кольори, іконки, написи)…",
    "Pobieram „{n}”: {x} z {razem}": "Завантажую «{n}»: {x} з {razem}",
    "Możesz zamknąć tę kartę, ale nie aplikację. Po zerwaniu połączenia pobieranie samo spróbuje jeszcze raz.": "Можна закрити цю картку, але не застосунок. Якщо з'єднання обірветься, завантаження саме спробує ще раз.",
    "Przerwij": "Перервати",
    "Pobierz mapę": "Завантажити мапу",
    "Sprawdź bez internetu": "Перевірити без інтернету",
    "dojście trasą ok. {d} min, zagrożenie za {eta} min": "дорога маршрутом бл. {d} хв, загроза за {eta} хв",
    "dojście ok. {d} min, zagrożenie za {eta} min": "дорога бл. {d} хв, загроза за {eta} хв",
    "Najpierw ustal pozycję (przycisk TERAZ, adres albo „Jestem w”) — wtedy symulacja porówna czas dojścia z czasem do zagrożenia.": "Спершу визначте позицію (кнопка ЗАРАЗ, адреса або «Я в»), — тоді симуляція порівняє час дороги з часом до загрози.",
    "Według szacunku nie zdążysz:": "За оцінкою ви не встигнете:",
    "Na górze ekranu są zasady z poradnika na taką sytuację.": "Угорі екрана — правила з порадника для такої ситуації.",
    "Według szacunku zdążysz: {zdanie}. To szacunek, nie gwarancja.": "За оцінкою ви встигнете: {zdanie}. Це оцінка, не гарантія.",
    "Czas z alarmu Strażnika": "Час із тривоги Strażnik",
    "Zagrożenie za <b>{eta} min</b> — ta sama wartość, którą pokazuje Strażnik.": "Загроза за <b>{eta} хв</b> — те саме значення, що показує Strażnik.",
    "Alarm opiera się na źródłach pośrednich, więc Grota nie porównuje go z czasem dojścia.": "Тривога ґрунтується на непрямих джерелах, тож Grota не порівнює її з часом дороги.",
    "Strażnik nie podaje teraz czasu do zagrożenia. Grota go nie zgaduje — pokazuje odległości i kierunek.": "Strażnik зараз не подає часу до загрози. Grota його не вгадує — показує відстані й напрямок.",
    "Symulacja ostrzeżenia Strażnika": "Симуляція попередження Strażnik",
    "prototyp": "прототип",
    "Po połączeniu ze Strażnikiem czas przyjdzie z alarmu. Grota porówna go z czasem dojścia — jeśli nie zdążysz, zamiast prowadzić pokaże zasady z „Poradnika” (s. 29). Wybierz, za ile minut zagrożenie:": "У зв'язці зі Strażnik час прийде з тривоги. Grota порівняє його з часом дороги — якщо не встигаєте, замість ведення покаже правила з порадника (с. 29). Виберіть, за скільки хвилин загроза:",
    "Ustalam Twoją pozycję…": "Визначаю вашу позицію…",
    "Nie chcesz czekać? Wybierz, gdzie jesteś:": "Не хочете чекати? Виберіть, де ви:",
    "Dotknij mapy w miejscu, w którym jesteś.": "Торкніться мапи в місці, де ви є.",
    "Jesteś poza zasięgiem danych Groty.": "Ви поза зоною даних Grota.",
    "Wybrane miejsce leży poza Polską.": "Вибране місце лежить поза Польщею.",
    "Według pozycji z telefonu jesteś poza Polską.": "За позицією з телефону ви поза Польщею.",
    "Grota zna miejsca schronienia tylko w Polsce — najbliższe jest {d} stąd, więc nie wyznacza trasy. Poza Polską stosuj się do komunikatów tamtejszych służb.": "Grota знає укриття лише в Польщі — найближче за {d}, тож маршруту не прокладає. Поза Польщею виконуйте вказівки місцевих служб.",
    "Jesteś w Polsce, tuż przy granicy? Telefon mógł podać złą pozycję — wybierz, gdzie jesteś:": "Ви в Польщі, біля самого кордону? Телефон міг подати неправильну позицію — виберіть, де ви:",
    "Pokaż mimo to": "Усе одно показати",
    "Pozycja przybliżona ({acc}) — wynik może dotyczyć innego miejsca.": "Приблизна позиція ({acc}) — результат може стосуватися іншого місця.",
    "zagrożenie może być bliżej niż czas dojścia": "загроза може бути ближчою, ніж час дороги",
    "To szacunek Groty, nie gwarancja — te same minuty pokazuje pasek na dole ekranu.": "Це оцінка Grota, не гарантія — ті самі хвилини показує панель унизу екрана.",
    "Wczytuję punkty schronienia — za chwilę pokażę najbliższe. Zasady niżej działają już teraz.": "Завантажую пункти укриття — за мить покажу найближчі. Правила нижче вже працюють.",
    "Nie zaznaczono żadnego rodzaju dostępu — zaznacz co najmniej jeden powyżej.": "Не позначено жодного типу доступу — позначте щонайменше один вище.",
    "punkt|punkty|punktów": ["пункт", "пункти", "пунктів"],
    "Bliżej jest {ile} o wątpliwym położeniu (najbliższy {d}) — Grota do nich nie prowadzi, bo szpilka stoi obok budynku albo w innym miejscu niż adres.": "Ближче є {ile} із сумнівним розташуванням (найближчий за {d}) — Grota до них не веде, бо шпилька стоїть поруч із будівлею або не там, де адреса.",
    "Inne opcje": "Інші варіанти",
    "GDZIE SIĘ SCHRONIĆ TERAZ": "ДЕ СХОВАТИСЯ ЗАРАЗ",
    "Ustalę Twoją pozycję i wskażę najbliższe sprawdzone miejsce schronienia. Trasę poprowadzi Google Maps.": "Визначу вашу позицію й покажу найближче перевірене укриття. Маршрутом поведе Google Maps.",
    "Przygotuj się": "Підготуйтеся",
    "Listy są cytatem z „Poradnika bezpieczeństwa”. Zaznaczaj, co już masz — postęp zostaje tylko na tym urządzeniu.": "Списки — цитата з «Poradnik bezpieczeństwa» (Порадника з безпеки). Позначайте, що вже маєте, — прогрес лишається лише на цьому пристрої.",
    "Zrobione: {n} z {razem}.": "Зроблено: {n} з {razem}.",
    "Miejsce w budynku dla domu, pracy i szkoły zapiszesz w zakładce „Moje miejsca”.": "Місце в будівлі для дому, роботи й школи збережете у вкладці «Мої місця».",
    "Dodaj dom, pracę lub szkołę w zakładce „Moje miejsca” — zapiszesz tam też swoje miejsce w budynku.": "Додайте дім, роботу чи школу у вкладці «Мої місця» — там же збережете своє місце в будівлі.",
    "Grota jest przetłumaczona przez autora aplikacji. Cytaty z „Poradnika bezpieczeństwa” to nasze tłumaczenie — oficjalny Poradnik jest tylko po polsku, a odnośniki prowadzą do polskiego oryginału. Adresy i nazwy miejsc zostają po polsku, tak jak na tabliczkach.": "Grota переклав автор застосунку. Цитати з «Poradnik bezpieczeństwa» (Порадника з безпеки) — наш переклад: офіційний порадник існує лише польською, а посилання ведуть до польського оригіналу. Адреси й назви місць лишаються польською, як на табличках.",
    "Zasady Groty": "Правила Grota",
    "Grota nie tworzy własnych procedur. Każde zalecenie pochodzi z „Poradnika bezpieczeństwa” (Rząd RP, nr publikacji 1/2025) i ma numer strony. Nazwy rozdziałów są z poradnika, podtytuły dodaliśmy sami, żeby odróżnić zalecenia z tego samego rozdziału.": "Grota не створює власних процедур. Кожна рекомендація походить з «Poradnik bezpieczeństwa» (Порадника з безпеки, уряд Польщі, публікація № 1/2025) і має номер сторінки. Назви розділів — з порадника, підзаголовки ми додали самі, щоб розрізняти рекомендації з одного розділу.",
    "Czego poradnik nie określa": "Чого порадник не визначає",
    "Poradnik nie podaje progu minut, po którym nie zdążysz dojść do schronienia, ani nie wskazuje środka transportu na czas ataku. Grota tego nie dopowiada: pokazuje szacunki i cytuje zasady.": "Порадник не називає кількості хвилин, після якої ви не встигнете дійти до укриття, і не радить способу пересування під час атаки. Grota цього не домислює: показує оцінки й цитує правила.",
    "Dlaczego w Grocie nie ma „schronów”": "Чому в Grota немає «сховищ»",
    "Inwentaryzacja Państwowej Straży Pożarnej z lat 2022–2023 wykazała w Polsce 1 903 schrony, 8 719 ukryć i 224 113 miejsc doraźnego schronienia. Publiczny zbiór „Punkty schronienia w Polsce”, na którym opiera się Grota, <b>nie rozróżnia tych kategorii</b> — wszystkie rekordy mają ten sam rodzaj.": "Інвентаризація Державної пожежної служби у 2022–2023 роках виявила в Польщі 1 903 сховища, 8 719 укриттів і 224 113 місць тимчасового укриття. Відкритий набір даних «Punkty schronienia w Polsce» (Пункти укриття в Польщі), на якому ґрунтується Grota, <b>не розрізняє цих категорій</b> — усі записи мають однаковий тип.",
    "art. 113 ustawy o ochronie ludności i obronie cywilnej": "ст. 113 закону про захист населення та цивільну оборону",
    "Art. 114": "Ст. 114",
    "Pełne dane, w tym rodzaj obiektu, pojemność i stan techniczny, trafiają do Centralnej Ewidencji Obiektów Zbiorowej Ochrony (CEOZO), którą prowadzi Komendant Główny PSP. Zgodnie z {a113} dane z tej ewidencji <b>nie są informacją publiczną</b>, a część z nich ma klauzulę „zastrzeżone”. {a114} przewiduje do wiadomości publicznej tylko ogólne dane dla województw i powiatów oraz informowanie o położeniu obiektów.": "Повні дані, зокрема тип об'єкта, місткість і технічний стан, потрапляють до Центрального реєстру об'єктів колективного захисту (CEOZO), який веде Головний комендант PSP. Згідно зі {a113} дані цього реєстру <b>не є публічною інформацією</b>, а частина з них має гриф «для службового користування». {a114} передбачає оприлюднення лише загальних даних для воєводств і повітів та інформування про розташування об'єктів.",
    "Dlatego Grota pokazuje punkty schronienia bez etykiety „schron”. Oznaczanie ich na podstawie map społecznościowych byłoby zgadywaniem: obiekty opisane w OpenStreetMap jako bunkry to w większości fortyfikacje z wojen i ruiny. Jeśli PSP udostępni rodzaj obiektu, dodamy go razem z datą weryfikacji.": "Тому Grota показує пункти укриття без позначки «сховище». Позначати їх на основі громадських мап було б вгадуванням: об'єкти, описані в OpenStreetMap як бункери, — здебільшого воєнні укріплення й руїни. Якщо PSP оприлюднить тип об'єкта, ми додамо його разом із датою перевірки.",
    "Źródła:": "Джерела:",
    "ustawa z 5.12.2024 o ochronie ludności i obronie cywilnej": "закон від 5.12.2024 про захист населення та цивільну оборону",
    "rozporządzenie MSWiA z 7.07.2025 o CEOZO": "розпорядження МВС Польщі від 7.07.2025 про CEOZO",
    "zbiór „Punkty schronienia w Polsce” na dane.gov.pl": "набір «Punkty schronienia w Polsce» на dane.gov.pl",
    "Twoje dane": "Ваші дані",
    "Miejsca, notatki, nagrane trasy i ustawienia zapisują się <b>tylko w pamięci tego urządzenia</b>. Autor aplikacji ich nie widzi i nigdzie nie wysyła.": "Місця, нотатки, записані маршрути й налаштування зберігаються <b>лише в пам'яті цього пристрою</b>. Автор застосунку їх не бачить і нікуди не надсилає.",
    "Kopia zapasowa iCloud może przenieść je na Twoje konto Apple.": "Резервна копія iCloud може перенести їх на ваш обліковий запис Apple.",
    "Kopia zapasowa Androida może przenieść je na Twoje konto Google.": "Резервна копія Android може перенести їх на ваш обліковий запис Google.",
    "Co opuszcza telefon i kiedy: wpisany adres trafia do wyszukiwarki GUGiK; przy wyznaczaniu trasy Twoja pozycja i cel idą do serwera tras FOSSGIS; współrzędne punktu do usługi zdjęć GUGiK; oglądany fragment mapy do OpenFreeMap; po naciśnięciu „Prowadź” albo „Street View” — do Google. Bez tych czynności nic nie wychodzi z telefonu.": "Що залишає телефон і коли: введена адреса йде до пошуку адрес GUGiK; під час прокладання маршруту ваша позиція й мета йдуть на сервер маршрутів FOSSGIS; координати пункту — до сервісу знімків GUGiK; фрагмент мапи, який ви переглядаєте, — до OpenFreeMap; після натискання «Вести» або «Street View» — до Google. Без цих дій ніщо не залишає телефон.",
    "Ograniczenia danych": "Обмеження даних",
    "Publiczny zbiór PSP nie podaje rodzaju obiektu, liczby miejsc ani tego, czy obiekt jest teraz otwarty. „Na żądanie” oznacza, że ktoś musi go otworzyć.": "Відкритий набір PSP не подає типу об'єкта, кількості місць і того, чи об'єкт зараз відчинений. «На вимогу» означає, що хтось мусить його відчинити.",
    "Położenie sprawdzamy automatycznie: czy punkt stoi na budynku, czy zgadza się z adresem, czy leży we właściwej gminie i województwie. Punkty wątpliwe (czerwona obwódka) nie są polecane jako pierwsze; „do sprawdzenia” (żółta) to drobniejsze rozbieżności. To nie jest kontrola obiektu przez urząd.": "Розташування ми перевіряємо автоматично: чи пункт стоїть на будівлі, чи збігається з адресою, чи лежить у правильній гміні та воєводстві. Сумнівні пункти (червона обвідка) не пропонуються першими; «перевірити» (жовта) — дрібніші розбіжності. Це не перевірка об'єкта органами влади.",
    "Przesunięte szpilki — błąd źródła, nie Groty": "Зміщені шпильки — помилка джерела, не Grota",
    "W publicznym zbiorze PSP część punktów ma współrzędne postawione obok budynku, którego dotyczą. Sprawdziliśmy to na danych z całej Polski: <b>1075 punktów</b> (1,3%) nie stoi na żadnym budynku. Przy 657 z nich budynek jest w promieniu 30 m (najczęściej blok — szpilka wylądowała na podwórku, parkingu albo trawniku), przy 252 w 30–60 m, przy 115 w 60–150 m, a <b>51 punktów nie ma żadnego budynku w promieniu 150 m</b> — tam szpilka wskazuje pole, las albo miejsce poza miejscowością z adresu.": "У відкритому наборі PSP частина пунктів має координати, поставлені поруч із будівлею, якої вони стосуються. Ми перевірили це на даних з усієї Польщі: <b>1075 пунктів</b> (1,3%) не стоять на жодній будівлі. Для 657 з них будівля є в радіусі 30 м (найчастіше багатоповерхівка — шпилька опинилася у дворі, на парковці чи газоні), для 252 — у 30–60 м, для 115 — у 60–150 м, а <b>51 пункт не має жодної будівлі в радіусі 150 м</b> — там шпилька вказує на поле, ліс або місце поза населеним пунктом з адреси.",
    "To błąd danych źródłowych i ich dalszego przetwarzania, nie Groty. Nie przesuwamy punktów po cichu, bo nie mamy czym potwierdzić, gdzie naprawdę jest schronienie. Zamiast tego: oznaczamy je, nie polecamy jako pierwszych i przy każdym piszemy, co stoi najbliżej szpilki i jak daleko — żeby w terenie szukać budynku, a nie kropki na mapie.": "Це помилка вихідних даних та їх подальшої обробки, а не Grota. Ми не пересуваємо пунктів потай, бо не маємо чим підтвердити, де насправді укриття. Натомість позначаємо їх, не пропонуємо першими й біля кожного пишемо, що стоїть найближче до шпильки і як далеко, — щоб на місці шукати будівлю, а не крапку на мапі.",
    "Jeśli widzisz punkt postawiony w złym miejscu, zgłoś to gminie albo komendzie PSP, która przekazuje dane do zbioru — poprawka u źródła naprawia go we wszystkich aplikacjach naraz.": "Якщо бачите пункт, поставлений не в тому місці, повідомте гміну або комендатуру PSP, яка передає дані до набору, — виправлення в джерелі виправляє його в усіх застосунках одразу.",
    "Czas dojścia to szacunek: zanim trasa się wyznaczy — z odległości w linii prostej, potem z trasy po drogach i ścieżkach (bez korków i utrudnień). Nie jest gwarancją.": "Час дороги — це оцінка: доки маршрут не прокладено — за відстанню по прямій, потім — за маршрутом дорогами й стежками (без заторів і перешкод). Це не гарантія.",
    "Źródła": "Джерела",
    "wersja internetowa na gov.pl": "інтернет-версія на gov.pl",
    "Zasady i listy kontrolne: {autorzy}, „{tytul}”, {wydanie}, {wersja}, licencja {licencja}.": "Правила й контрольні списки: {autorzy}, «{tytul}», {wydanie}, {wersja}, ліцензія {licencja}.",
    "{zrodlo}; dane z {data}. Kontrola budynków: {kontrola}. Mapa: OpenFreeMap, © OpenStreetMap. Zdjęcia z góry: ortofotomapa GUGiK (usługa WMS, pobierana na bieżąco, bez zapisywania). Biblioteka mapy: MapLibre (BSD).": "{zrodlo}; дані від {data}. Перевірка будівель: {kontrola}. Мапа: OpenFreeMap, © OpenStreetMap. Знімки згори: ортофотомапа GUGiK (сервіс WMS, завантажується наживо, без збереження). Бібліотека мапи: MapLibre (BSD).",
    "Wyszukiwanie adresów: usługa geokodowania GUGiK (zapytanie wysyłane dopiero po naciśnięciu „Szukaj”). Spis miejscowości do wyszukiwania bez internetu: OpenStreetMap (© współtwórcy OSM, ODbL). Ikony: Lucide (licencja ISC).": "Пошук адрес: сервіс геокодування GUGiK (запит надсилається лише після натискання «Шукати»). Список населених пунктів для пошуку без інтернету: OpenStreetMap (© учасники OSM, ODbL). Іконки: Lucide (ліцензія ISC).",
    "Wstępna trasa na mapie: serwer tras FOSSGIS (OSRM, dane © współtwórcy OpenStreetMap) — pozycja i cel są wysyłane do tego serwera; trasa nie uwzględnia korków ani utrudnień.": "Попередній маршрут на мапі: сервер маршрутів FOSSGIS (OSRM, дані © учасники OpenStreetMap) — позиція й мета надсилаються на цей сервер; маршрут не враховує заторів і перешкод.",
    "Popraw mapę": "Виправити мапу",
    "Rodzaj budynku (szkoła, blok, parking podziemny…): OpenStreetMap, nie dane PSP.": "Тип будівлі (школа, багатоповерхівка, підземна парковка…): OpenStreetMap, не дані PSP.",
    "„W określonych godzinach” i „na żądanie”": "«У визначені години» і «на вимогу»",
    "Według komunikatów PSP i samorządów o aplikacji „Gdzie się ukryć”: obiekty z godzinami są dostępne w czasie pracy placówki lub obecności obsługi, a obiekty „na żądanie” są zamknięte (np. piwnice bloków, garaże wspólnot) i w razie zagrożenia powinni je otworzyć zarządcy lub mieszkańcy w ramach wzajemnej pomocy. Publiczne dane nie podają godzin ani kontaktu — zapytaj zarządcę budynku zawczasu i zapisz odpowiedź przy swoim miejscu schronienia.": "Згідно з повідомленнями PSP та органів місцевого самоврядування про застосунок «Gdzie się ukryć» (Де сховатися): об'єкти з годинами доступні під час роботи установи або присутності персоналу, а об'єкти «на вимогу» зачинені (напр. підвали багатоповерхівок, гаражі житлових спільнот) і в разі загрози їх мають відчинити управителі або мешканці в порядку взаємодопомоги. Відкриті дані не подають годин і контактів — запитайте управителя будівлі заздалегідь і запишіть відповідь біля свого укриття.",
    "brak w pobliżu": "немає поблизу",
    "Rodzaj budynku: wszystkie": "Тип будівлі: усі",
    "Rodzaj budynku: {n} z {w}": "Тип будівлі: {n} з {w}",
    "zapisuję…": "зберігаю…",
    "Wpisz adres albo wskaż miejsce na mapie.": "Введіть адресу або вкажіть місце на мапі.",
    "Usunąć nagraną trasę?": "Видалити записаний маршрут?",
    "Możesz też ustalić pozycję na ekranie TERAZ albo wskazać ją na mapie.": "Можна також визначити позицію на екрані ЗАРАЗ або вказати її на мапі.",
    "Usunąć miejsce „{n}” razem z zapisanymi schronieniami i notatkami?": "Видалити місце «{n}» разом зі збереженими укриттями й нотатками?",
    "Wskaż miejsce na mapie.": "Вкажіть місце на мапі.",
    "zapisane miejsce „{n}”": "збережене місце «{n}»",
    "Wczytuję punkty schronienia…": "Завантажую пункти укриття…",
    "budynek": "будівля",
    "nie ma żadnego budynku w promieniu 150 m — współrzędne są prawdopodobnie błędne": "у радіусі 150 м немає жодної будівлі — координати, ймовірно, хибні",
    "szpilka stoi obok budynku, nie na nim — najbliżej {co}, {m} m stąd": "шпилька стоїть поруч із будівлею, а не на ній — найближче {co}, за {m} м",
    "szpilka nie stoi przy żadnym budynku — najbliższy ({co}) jest {m} m stąd": "шпилька не стоїть біля жодної будівлі — найближча ({co}) за {m} м",
    "punkt leży w innym województwie niż podane w danych": "пункт лежить в іншому воєводстві, ніж указано в даних",
    "innej gminie": "іншій гміні",
    "dane podają gminę {g}, a punkt leży w: {gdzie}": "дані вказують гміну {g}, а пункт лежить у: {gdzie}",
    "adres z danych jest {km} km od punktu": "адреса з даних за {km} км від пункту",
    "adres z danych jest {m} m od punktu — sprawdź na miejscu": "адреса з даних за {m} м від пункту — перевірте на місці",
    "miejscowość o tej nazwie jest {km} km dalej (nazwy bywają powtarzalne)": "населений пункт із цією назвою за {km} км (назви бувають однакові)",
    "dane PSP nie podają gminy": "дані PSP не вказують гміни",
    "Położenie wątpliwe: {co}.": "Сумнівне розташування: {co}.",
    "Do sprawdzenia: {co}.": "Перевірити: {co}.",
    "Położenie sprawdzone automatycznie: punkt stoi na budynku, zgadza się z adresem.": "Розташування перевірено автоматично: пункт стоїть на будівлі, збігається з адресою.",
    "Położenie sprawdzone automatycznie: punkt stoi na budynku.": "Розташування перевірено автоматично: пункт стоїть на будівлі.",
    "Położenie sprawdzone automatycznie: punkt {m} m od budynku, zgadza się z adresem.": "Розташування перевірено автоматично: пункт за {m} м від будівлі, збігається з адресою.",
    "Położenie sprawdzone automatycznie: punkt {m} m od budynku.": "Розташування перевірено автоматично: пункт за {m} м від будівлі.",
    "nr {n}": "№ {n}",
    "pow. {p}": "повіт {p}",
    "cała ulica — pozycja przybliżona": "уся вулиця — приблизна позиція",
    "tego numeru nie ma w bazie adresów — sprawdź położenie na mapie": "цього номера немає в базі адрес — перевірте розташування на мапі",
    "Bez internetu nie sprawdzę, jakie mapy są do pobrania.": "Без інтернету не перевірю, які мапи можна завантажити.",
    "Serwer map nie podał spisu (kod {k}).": "Сервер мап не надав списку (код {k}).",
    "Serwer map podał spis w nieznanym formacie.": "Сервер мап надав список у невідомому форматі.",
    "serwer nie obsługuje pobierania zakresami": "сервер не підтримує завантаження частинами",
    "kod {k}": "код {k}",
    "paczka na serwerze nie zgadza się ze spisem": "пакет на сервері не збігається зі списком",
    "niepełny kawałek": "неповний фрагмент",
    "brak połączenia": "немає з'єднання",
    "Nie udało się pobrać fragmentu mapy ({powod}).": "Не вдалося завантажити фрагмент мапи ({powod}).",
    "Paczka na serwerze ma nieznany format.": "Пакет на сервері має невідомий формат.",
    "Pobrany fragment mapy jest uszkodzony — spróbuj jeszcze raz.": "Завантажений фрагмент мапи пошкоджено — спробуйте ще раз.",
    "Pieszo": "Пішки",
    "Rower / hulajnoga": "Велосипед / самокат",
    "Rower": "Велосипед",
    "Samochód / motocykl": "Автомобіль / мотоцикл",
    "Samochód": "Автомобіль",
    "Całodobowo": "Цілодобово",
    "Według PSP obiekt jest dostępny całą dobę.": "За даними PSP об'єкт доступний цілодобово.",
    "W określonych godzinach": "У визначені години",
    "Dostępny tylko w godzinach pracy obiektu lub obecności obsługi. Godzin nie ma w publicznych danych — sprawdź je wcześniej u zarządcy.": "Доступний лише в години роботи об'єкта або коли присутній персонал. Годин немає у відкритих даних — дізнайтеся їх заздалегідь в управителя.",
    "Na żądanie": "На вимогу",
    "Obiekt zamknięty (np. piwnica bloku, garaż). Zarządca lub mieszkańcy powinni go otworzyć w razie zagrożenia — nie zakładaj, że będzie otwarty. Zapytaj zarządcę wcześniej.": "Зачинений об'єкт (напр. підвал багатоповерхівки, гараж). Управитель або мешканці мають відчинити його в разі загрози — не розраховуйте, що він буде відчинений. Запитайте управителя заздалегідь.",
    "Brak informacji": "Немає інформації",
    "Dom": "Дім",
    "Praca": "Робота",
    "Szkoła / uczelnia": "Школа / університет",
    "Przedszkole / żłobek": "Дитсадок / ясла",
    "Rodzina / bliscy": "Родина / близькі",
    "Działka / domek": "Дача / будиночок",
    "Inne": "Інше",
    "Sygnały alarmowe i komunikaty ostrzegawcze": "Сигнали тривоги та попереджувальні повідомлення",
    "co robić po usłyszeniu sygnału": "що робити, почувши сигнал",
    "Jeśli usłyszysz sygnał alarmowy, włącz radio lub telewizor i stosuj się do komunikatów.": "Якщо почуєте сигнал тривоги, увімкніть радіо чи телевізор і виконуйте повідомлення.",
    "Atak z powietrza": "Повітряна атака",
    "droga do schronienia": "шлях до укриття",
    "Kiedy usłyszysz sygnał alarmowy, idź ustaloną wcześniej drogą ewakuacyjną do miejsca schronienia. Zabierz ze sobą plecak ewakuacyjny. Unikaj wind, idź schodami. Schronienie, do którego się udajesz, powinno być bez okien, mieć grube ściany, gruby strop, dostęp do powietrza i wyjście awaryjne.": "Почувши сигнал тривоги, ідіть заздалегідь визначеним евакуаційним шляхом до укриття. Візьміть із собою тривожний рюкзак. Уникайте ліфтів, ідіть сходами. Укриття, до якого ви йдете, має бути без вікон, мати товсті стіни, товсте перекриття, доступ повітря й аварійний вихід.",
    "Schronienia": "Укриття",
    "gdy nie zdążysz do punktu schronienia": "якщо не встигаєте до пункту укриття",
    "Jeśli nie możesz ukryć się w oznaczonym miejscu schronienia, zostań w domu – z dala od okien, przy ścianach nośnych, w centralnych pomieszczeniach.": "Якщо не можете сховатися в позначеному укритті, залишайтеся вдома – подалі від вікон, біля несучих стін, у центральних приміщеннях.",
    "gdy jesteś poza domem": "якщо ви не вдома",
    "Jeśli jesteś poza domem, szukaj miejsc, które zapewniają przynajmniej minimum ochrony (najniższe kondygnacje budynków, w tym piwnice, garaże podziemne, tunele, przejścia podziemne). Nawet zwykłe zagłębienia terenu zapewniają lepszą ochronę niż przebywanie na otwartej przestrzeni.": "Якщо ви не вдома, шукайте місця, які дають хоча б мінімальний захист (найнижчі поверхи будівель, зокрема підвали, підземні гаражі, тунелі, підземні переходи). Навіть звичайні заглиблення рельєфу захищають краще, ніж перебування на відкритій місцевості.",
    "eksplozja w otwartym terenie": "вибух на відкритій місцевості",
    "Jeśli na otwartym terenie usłyszysz eksplozję, padnij na ziemię – najlepiej w zagłębieniu – i osłoń głowę.": "Якщо на відкритій місцевості почуєте вибух, упадіть на землю – найкраще в заглибленні – і прикрийте голову.",
    "po ataku": "після атаки",
    "Nie wychodź ze schronienia pochopnie. Nie przeciążaj linii telefonicznych – korzystaj z SMS-ów. Pomóż innym – sprawdź, kto wokół Ciebie potrzebuje wsparcia.": "Не виходьте з укриття поспіхом. Не перевантажуйте телефонних ліній – користуйтеся SMS. Допоможіть іншим – перевірте, хто довкола вас потребує підтримки.",
    "Przygotuj swoje otoczenie — Transport": "Підготуйте своє оточення — Транспорт",
    "samochód w kryzysie": "автомобіль під час кризи",
    "W sytuacjach kryzysowych ogranicz korzystanie z samochodu. Drogi powinny być przejezdne dla służb ratowniczych i transportów wojskowych. Miej przy sobie papierową mapę lub atlas samochodowy. Możesz wcześniej pobrać mapy offline. System GPS może nie działać.": "У кризових ситуаціях обмежте користування автомобілем. Дороги мають бути вільними для рятувальних служб і військового транспорту. Майте при собі паперову мапу або автомобільний атлас. Можна заздалегідь завантажити мапи офлайн. Система GPS може не працювати.",
    "Ewakuacja": "Евакуація",
    "gdy służby zarządzą ewakuację": "коли служби оголосять евакуацію",
    "Jeżeli władze lub służby ratownicze zdecydują o ewakuacji, bezwzględnie zastosuj się do poleceń. Informacje będziesz dostawać na bieżąco ze stron rządowych, Alertów RCB, RSO i mediów.": "Якщо влада або рятувальні служби вирішать провести евакуацію, неухильно виконуйте вказівки. Інформацію ви отримуватимете в реальному часі з урядових сайтів, попереджень RCB, RSO та медіа.",
    "gdzie szukać miejsc schronienia": "де шукати укриття",
    "Informacje o lokalizacji miejsc schronienia znajdziesz w urzędzie gminy, jednostce Państwowej lub Ochotniczej Straży Pożarnej oraz na stronie gov.pl/kgpsp. Schronienia są oznaczone specjalnym znakiem graficznym.": "Інформацію про розташування укриттів знайдете в управлінні гміни, у підрозділі Державної або Добровільної пожежної служби та на сайті gov.pl/kgpsp. Укриття позначені спеціальним графічним знаком.",
    "Dekalog bezpieczeństwa": "Декалог безпеки",
    "punkt z dekalogu": "пункт із декалогу",
    "Sprawdź, gdzie jest najbliższe miejsce schronienia.": "Дізнайтеся, де найближче укриття.",
    "Przygotuj swoje otoczenie — Dom lub mieszkanie": "Підготуйте своє оточення — Будинок або квартира",
    "najbezpieczniejsze miejsce w domu": "найбезпечніше місце вдома",
    "Sprawdź, które miejsce w domu jest najbezpieczniejsze: z dala od okien, przy ścianach nośnych, w centralnych pomieszczeniach.": "Визначте, яке місце вдома найбезпечніше: подалі від вікон, біля несучих стін, у центральних приміщеннях.",
    "Dom lub mieszkanie": "Будинок або квартира",
    "Przygotuj się na przerwy w dostawach wody, prądu, gazu i na brak dostępu do telefonu i internetu.": "Будьте готові до перебоїв у постачанні води, електроенергії, газу та до відсутності телефонного зв'язку й інтернету.",
    "Przygotuj przedmioty do uszczelniania i zabezpieczania okien i drzwi, np. koce, ręczniki, taśmy.": "Приготуйте речі для ущільнення й захисту вікон і дверей, напр. ковдри, рушники, стрічки.",
    "Usuń z korytarzy i klatek schodowych niepotrzebne przedmioty.": "Приберіть із коридорів і сходових клітин непотрібні речі.",
    "Oznacz w widoczny sposób, np. kolorowymi taśmami, miejsca odcięcia gazu, prądu i wody. Przećwicz z najbliższymi ich wyłączanie.": "Помітно позначте, напр. кольоровими стрічками, місця перекриття газу, електроенергії та води. Потренуйтеся з близькими їх вимикати.",
    "Zamontuj czujki dymu, czadu i gazu. Regularnie sprawdzaj ich stan techniczny. Dokładnie sprawdź umiejscowienie czujek.": "Встановіть датчики диму, чадного газу й газу. Регулярно перевіряйте їхній технічний стан. Ретельно перевірте, де розміщено датчики.",
    "Wyposaż dom w gaśnicę i koc gaśniczy.": "Облаштуйте дім вогнегасником і протипожежною ковдрою.",
    "Pamiętaj o regularnych przeglądach instalacji: kominowej, wentylacyjnej, gazowej i elektrycznej oraz o ubezpieczeniu domu/mieszkania.": "Пам'ятайте про регулярні перевірки димохідної, вентиляційної, газової та електричної систем і про страхування будинку/квартири.",
    "Zapasy domowe na minimum 3 dni": "Домашні запаси щонайменше на 3 дні",
    "Jedzenie i picie: minimum 3 litry wody na osobę na dobę, żywność gotowa do spożycia.": "Їжа й пиття: щонайменше 3 літри води на людину на добу, готова до вживання їжа.",
    "Apteczka: leki przyjmowane na stałe, przeciwbólowe, przeciwzapalne, przeciwwymiotne, przeciwbiegunkowe, gaza, bandaże, opatrunki na oparzenia, rękawiczki jednorazowe, środki antyseptyczne, opaska do tamowania krwotoków, termometr i nożyczki, maseczki FFP3, folia termiczna.": "Аптечка: ліки, які ви приймаєте постійно, знеболювальні, протизапальні, протиблювотні, протидіарейні засоби, марля, бинти, пов'язки від опіків, одноразові рукавички, антисептики, джгут для зупинки кровотечі, термометр і ножиці, маски FFP3, термоковдра.",
    "Środki czystości i higieny osobistej: papier toaletowy, chusteczki nawilżane, podpaski, pieluchy, środki dezynfekujące, worki na śmieci, wiadro z pokrywą.": "Засоби для прибирання й особистої гігієни: туалетний папір, вологі серветки, гігієнічні прокладки, підгузки, дезінфекційні засоби, мішки для сміття, відро з кришкою.",
    "Oświetlenie i łączność: latarka i radio na baterie lub na korbkę, naładowany telefon, ładowarka, naładowany powerbank, pasujące kable i baterie, świeczki do użytku domowego, zapalniczka.": "Освітлення й зв'язок: ліхтарик і радіо на батарейках або з ручним приводом, заряджений телефон, зарядний пристрій, заряджений павербанк, відповідні кабелі й батарейки, побутові свічки, запальничка.",
    "Koce, śpiwory i ciepła odzież.": "Ковдри, спальники й теплий одяг.",
    "Gotówka w różnych nominałach.": "Готівка різними номіналами.",
    "Narzędzia i sprzęt: taśmy, folie, zestawy do uszczelniania.": "Інструменти й приладдя: стрічки, плівки, набори для ущільнення.",
    "Alternatywne źródło ogrzewania, które nie działa na prąd.": "Альтернативне джерело опалення, що працює без електрики.",
    "Plecak ewakuacyjny": "Тривожний рюкзак",
    "Przygotuj podręczny zestaw najbardziej potrzebnych rzeczy. Skorzystaj z naszej listy i dopasuj ją do swoich potrzeb. Plecak ewakuacyjny powinien mieć każdy domownik, nawet dzieci.": "Підготуйте під рукою набір найпотрібніших речей. Скористайтеся нашим списком і пристосуйте його до своїх потреб. Тривожний рюкзак повинен мати кожен член родини, навіть діти.",
    "Woda butelkowana. Filtry lub tabletki do uzdatniania wody.": "Бутильована вода. Фільтри або таблетки для знезараження води.",
    "Apteczka i leki osobiste, środki higieniczne i do dezynfekcji.": "Аптечка й особисті ліки, засоби гігієни й дезінфекції.",
    "Dokumenty, kopie na pendrivie i gotówka w różnych nominałach.": "Документи, копії на флешці й готівка різними номіналами.",
    "Latarka i radio na baterie lub na korbkę, naładowany telefon i powerbank, ładowarka, pasujące kable i zapasowe baterie.": "Ліхтарик і радіо на батарейках або з ручним приводом, заряджені телефон і павербанк, зарядний пристрій, відповідні кабелі й запасні батарейки.",
    "Scyzoryk lub multitool, zapalniczka, worki na śmieci, mapy drukowane.": "Складаний ніж або мультитул, запальничка, мішки для сміття, друковані мапи.",
    "Żywność wysokoodżywcza gotowa do spożycia (batony energetyczne, suszone owoce, bakalie itp.).": "Висококалорійна готова їжа (енергетичні батончики, сухофрукти, горіхи тощо).",
    "Ważna rzecz osobista, np. zdjęcie, pamiątka rodzinna.": "Важлива особиста річ, напр. фотографія, родинна пам'ятка.",
    "Ubranie dopasowane do pory roku, odzież przeciwdeszczowa, śpiwór, karimata, folia termiczna.": "Одяг відповідно до пори року, дощовик, спальник, каримат, термоковдра.",
    "Alternatywna łączność (np. walkie-talkie).": "Альтернативний зв'язок (напр. рація).",
    "Plan na kryzys": "План на випадок кризи",
    "Opracuj rodzinny plan na wypadek kryzysu.": "Складіть родинний план на випадок кризи.",
    "Ustal dane kontaktowe oraz miejsca i terminy spotkań – w okolicy i poza miejscowością zamieszkania. To ważne na wypadek rozdzielenia i braku łączności.": "Домовтеся про контакти, а також місця й час зустрічей – поблизу й поза вашим населеним пунктом. Це важливо на випадок, якщо ви розлучитеся й не матимете зв'язку.",
    "Regularnie go aktualizuj i ćwicz z domownikami.": "Регулярно оновлюйте його й відпрацьовуйте з рідними.",
    "Sprawdź, gdzie są wyjścia ewakuacyjne, miejsca zbiórki, gaśnice, defibrylatory (AED) i apteczki.": "Дізнайтеся, де евакуаційні виходи, місця збору, вогнегасники, дефібрилятори (AED) і аптечки.",
    "Zgłaszaj natychmiast nieprawidłowości, które zauważysz, np. uszkodzoną instalację elektryczną, zablokowane drogi ewakuacyjne, niesprawne windy.": "Негайно повідомляйте про помічені несправності, напр. пошкоджену електропроводку, заблоковані евакуаційні шляхи, несправні ліфти.",
    "Przećwiczcie ze współpracownikami plan awaryjny i ewakuację. Upewnij się, że wiesz, jak rozpoznawać, zapobiegać, alarmować i reagować na zagrożenia w Twojej pracy.": "Відпрацюйте з колегами аварійний план і евакуацію. Переконайтеся, що знаєте, як розпізнавати загрози на роботі, запобігати їм, повідомляти про них і реагувати.",
    "Szkoła": "Школа",
    "Jeżeli uczysz się w szkole, bierz udział w próbnych alarmach. Informuj nauczycieli o podejrzanych zachowaniach lub przedmiotach.": "Якщо ви навчаєтеся в школі, беріть участь у навчальних тривогах. Повідомляйте вчителів про підозрілу поведінку або предмети.",
    "Jeżeli Twoje dziecko jest uczniem, zapisz kontakt do osoby wyznaczonej przez szkołę w sprawie odbioru dzieci w sytuacji zagrożenia.": "Якщо ваша дитина — учень, запишіть контакт особи, яку школа призначила відповідальною за передачу дітей батькам у разі загрози.",
    "Osoby potrzebujące szczególnej pomocy": "Люди, які потребують особливої допомоги",
    "W sytuacjach kryzysowych pomóż osobom starszym, chorym czy z niepełnosprawnościami. Nie wszyscy mogą być świadomi nadchodzącego zagrożenia, dlatego przekaż im najważniejsze informacje i wyjaśnij, co trzeba zrobić.": "У кризових ситуаціях допоможіть літнім, хворим людям чи людям з інвалідністю. Не всі можуть знати про загрозу, що наближається, тож передайте їм найважливішу інформацію й поясніть, що потрібно зробити.",
    "Ustal z osobą, którą wspierasz, sposób działania w sytuacji kryzysowej.": "Домовтеся з людиною, якій допомагаєте, як діяти в кризовій ситуації.",
    "Pomóż w przygotowaniach, np. spakuj plecak ewakuacyjny dla osoby wspieranej, upewnij się, że ma zapas niezbędnych leków i baterii do urządzeń wspomagających (aparat słuchowy, sensor do pomiaru cukru itp.).": "Допоможіть із підготовкою, напр. зберіть тривожний рюкзак для людини, якій допомагаєте, переконайтеся, що вона має запас потрібних ліків і батарейок для допоміжних пристроїв (слуховий апарат, сенсор рівня цукру тощо).",
    "W razie nagłego zagrożenia poinformuj służby ratownicze o osobie, która wymaga szczególnej pomocy podczas ewakuacji.": "У разі раптової загрози повідомте рятувальні служби про людину, яка потребує особливої допомоги під час евакуації.",
    "Cytaty bez zmian treści. Grota nie jest publikacją urzędową.": "Цитати без зміни змісту (у перекладі). Grota не є офіційним виданням.",
    "Uczelnia": "Університет",
    "Szpital / przychodnia": "Лікарня / поліклініка",
    "Urząd": "Установа",
    "Policja / straż / wojsko": "Поліція / пожежна служба / військо",
    "Kultura (dom kultury, kino, teatr, biblioteka)": "Культура (будинок культури, кіно, театр, бібліотека)",
    "Hala sportowa / basen": "Спортзал / басейн",
    "Kościół / świątynia": "Церква / храм",
    "Centrum handlowe": "Торговельний центр",
    "Sklep / centrum handlowe": "Магазин / торговельний центр",
    "Biurowiec / usługi": "Офісна будівля / послуги",
    "Hotel / akademik": "Готель / гуртожиток",
    "Dworzec / stacja / metro": "Вокзал / станція / метро",
    "Parking podziemny": "Підземна парковка",
    "Garaże / parking wielopoziomowy": "Гаражі / багаторівнева парковка",
    "Zakład / magazyn": "Підприємство / склад",
    "Blok mieszkalny": "Багатоквартирний будинок",
    "Dom jednorodzinny": "Приватний будинок",
    "Budynek gospodarczy / rolniczy": "Господарська / сільськогосподарська будівля",
    "Budynek publiczny": "Громадська будівля",
    "Budynek (rodzaj nieoznaczony w mapie)": "Будівля (тип не позначено на мапі)",
    "miasto": "місто",
    "wieś": "село",
    "osada / przysiółek": "селище / хутір",
    "dzielnica / osiedle": "район / житловий масив",
    "Parkingi podziemne i garaże": "Підземні парковки й гаражі",
    "Centra handlowe": "Торговельні центри",
    "Dworce, stacje, metro": "Вокзали, станції, метро",
    "Bloki mieszkalne": "Багатоквартирні будинки",
    "Domy i zabudowa wiejska": "Будинки й сільська забудова",
    "Szkoły, przedszkola, uczelnie": "Школи, дитсадки, університети",
    "Szpitale i przychodnie": "Лікарні й поліклініки",
    "Urzędy i służby": "Установи й служби",
    "Biura, sklepy, hotele, zakłady": "Офіси, магазини, готелі, підприємства",
    "Kultura, sport, świątynie": "Культура, спорт, храми",
    "Rodzaj nieznany": "Тип невідомий",
    "Sygnały alarmowe": "Сигнали тривоги",
    "Przygotuj swoje otoczenie": "Підготуйте своє оточення",
    "W godzinach": "У години",
    "Sprawdzone": "Перевірені",
    "Do sprawdzenia": "Перевірити",
    "Wątpliwe": "Сумнівні",
    "Chwilowo brak pozycji GPS — nagrywanie trwa.": "Тимчасово немає позиції GPS — запис триває.",
    "Brak zgody na lokalizację. Włącz ją w Ustawieniach iPhone'a: Ustawienia → Strażnik → Lokalizacja → „Podczas używania aplikacji”. Możesz też wybrać, gdzie jesteś, poniżej.": "Немає дозволу на геолокацію. Увімкніть її в Параметрах iPhone: Параметри → Strażnik → Локація → «Під час використання». Можна також вибрати, де ви, нижче.",
    "Telefon nie ustalił pozycji. Sprawdź, czy usługi lokalizacji są włączone (Ustawienia → Prywatność i ochrona → Usługi lokalizacji), albo wybierz, gdzie jesteś, poniżej.": "Телефон не визначив позиції. Перевірте, чи ввімкнено служби локації (Параметри → Приватність і безпека → Служби локації), або виберіть, де ви, нижче.",
    "Ustalanie pozycji trwało zbyt długo. Spróbuj jeszcze raz albo wskaż miejsce na mapie.": "Визначення позиції тривало задовго. Спробуйте ще раз або вкажіть місце на мапі.",
    "Brak zgody na lokalizację. Włącz ją w ustawieniach telefonu: Aplikacje → Strażnik → Uprawnienia → Lokalizacja. Możesz też wybrać, gdzie jesteś, poniżej.": "Немає дозволу на геолокацію. Увімкніть її в налаштуваннях телефону: Додатки → Strażnik → Дозволи → Місцезнаходження. Можна також вибрати, де ви, нижче.",
    "Telefon nie ustalił pozycji. Sprawdź, czy lokalizacja jest włączona (szybkie ustawienia u góry ekranu), albo wybierz, gdzie jesteś, poniżej.": "Телефон не визначив позиції. Перевірте, чи ввімкнено геолокацію (швидкі налаштування вгорі екрана), або виберіть, де ви, нижче.",
    "Brak zgody na lokalizację. Kliknij ikonę kłódki przy adresie strony i zezwól na lokalizację. Na komputerze z Windows sprawdź też: Ustawienia → Prywatność i zabezpieczenia → Lokalizacja (włączona, także dla przeglądarki).": "Немає дозволу на геолокацію. Натисніть значок замка біля адреси сторінки й дозвольте геолокацію. На комп'ютері з Windows перевірте також: Параметри → Конфіденційність і захист → Розташування (увімкнено, зокрема для браузера).",
    "Urządzenie nie ustaliło pozycji. Komputer bez GPS korzysta z sieci Wi-Fi — sprawdź, czy lokalizacja jest włączona w systemie.": "Пристрій не визначив позиції. Комп'ютер без GPS використовує мережі Wi-Fi — перевірте, чи ввімкнено геолокацію в системі.",
    "adres z bazy GUGiK": "адреса з бази GUGiK",
    "środek miejscowości (spis OpenStreetMap)": "центр населеного пункту (список OpenStreetMap)",
    "punkt wskazany na mapie": "точка, вказана на мапі",
    "miejsce wskazane na mapie": "місце, вказане на мапі",
    "Nie udało się wczytać punktów schronienia. Zasady i listy „Przygotuj się” działają bez nich.": "Не вдалося завантажити пункти укриття. Правила й списки «Підготуйтеся» працюють і без них.",
    "Najpierw ustal pozycję albo wybierz zapisane miejsce.": "Спершу визначте позицію або виберіть збережене місце.",
    "Dla tego obszaru nie ma jeszcze mapy do pobrania.": "Для цієї території ще немає мапи для завантаження.",
    "Lokalizacja działa tylko na stronie https albo localhost.": "Геолокація працює лише на сторінці https або localhost.",
    "Ta przeglądarka nie udostępnia lokalizacji.": "Цей браузер не надає геолокації.",
    "Pokaż punkty": "Показати пункти",
    "Filtr włączony — lista pokazuje tylko zaznaczone punkty. Odległości przy przyciskach liczone są od tego miejsca.": "Фільтр увімкнено — список показує лише позначені пункти. Відстані на кнопках рахуються від цього місця.",
    "Prowadź do punktów": "Вести до пунктів",
    "Filtr włączony — Grota prowadzi tylko do zaznaczonych punktów. Odległości przy przyciskach pokazują, ile dzieli Cię od najbliższego punktu każdego rodzaju.": "Фільтр увімкнено — Grota веде лише до позначених пунктів. Відстані на кнопках показують, як далеко до найближчого пункту кожного типу.",
    "Grota prowadzi tylko do punktów o sprawdzonym położeniu. Punkty wątpliwe pomija i pisze o nich pod propozycją.": "Grota веде лише до пунктів із перевіреним розташуванням. Сумнівні пункти пропускає й пише про них під пропозицією.",
    "Wpisz, gdzie jesteś": "Введіть, де ви",
    "Nowy adres": "Нова адреса",
    "Adres miejsca": "Адреса місця",
    "Adres albo miejscowość miejsca spotkania": "Адреса або населений пункт місця зустрічі",
    "albo wpisz adres / miejscowość": "або введіть адресу / населений пункт",
    "GPS nie działa? Wpisz adres albo miejscowość": "GPS не працює? Введіть адресу або населений пункт",
    "Wokół miejsca": "Навколо місця",
    "Cała Polska": "Уся Польща",
    "Zdjęcie z góry, ok. 140 m szerokości · punkt w środku · ortofotomapa GUGiK": "Знімок згори, бл. 140 м завширшки · пункт у центрі · ортофотомапа GUGiK",
    "Zdjęcie z góry · punkt w środku · ortofotomapa GUGiK": "Знімок згори · пункт у центрі · ортофотомапа GUGiK",
    "Komenda Główna PSP, dane.gov.pl, CC BY 4.0": "Головна комендатура Державної пожежної служби (KG PSP), dane.gov.pl, CC BY 4.0",
    "nr publikacji 1/2025": "публікація № 1/2025",
    "Komenda Główna PSP, „Punkty schronienia w Polsce”, dane.gov.pl, CC BY 4.0": "Головна комендатура Державної пожежної служби (KG PSP), «Punkty schronienia w Polsce» (Пункти укриття в Польщі), dane.gov.pl, CC BY 4.0",
    "{x} m": "{x} м",
    "{x} km": "{x} км",
    "{x} MB": "{x} МБ",
    "{x} GB": "{x} ГБ",
    "{m} min": "{m} хв",
    "Strażnik": "Strażnik",
    "Wróć do Strażnika": "Назад до Strażnik",
    "„Instrukcja reagowania” MSWiA, s. {s}": "«Instrukcja reagowania» (Інструкція реагування) МВС Польщі, с. {s}",
    "Piwnica lub garaż — na co patrzeć na miejscu": "Підвал або гараж — на що подивитися на місці",
    "Pamiętaj — zasady z poradnika i instrukcji": "Пам'ятайте — правила з порадника та інструкції",
    "Instrukcja reagowania MSWiA": "Інструкція реагування МВС Польщі",
    "Osobny materiał MSWiA i Państwowej Straży Pożarnej z 25 września 2026, nazwany przez ministerstwo rozwinięciem „Poradnika bezpieczeństwa”. Mówi to, czego w Poradniku nie ma: jak wybrać pomieszczenie i czego szukać w piwnicy albo garażu.": "Окремий матеріал МВС Польщі та Державної пожежної служби від 25 вересня 2026 року, який міністерство називає розвитком «Порадника з безпеки». Він каже те, чого в пораднику немає: як вибрати приміщення і на що дивитися в підвалі чи гаражі.",
    "plik PDF na gov.pl": "файл PDF на gov.pl",
    "Zasady oznaczone jako „Instrukcja reagowania”: {autorzy}, „{tytul}”, {wydanie}, {wersja}, licencja {licencja}. Cytaty przepisane zwykłym pismem — oryginał jest złożony wersalikami, słowa są bez zmian.": "Правила, позначені як «Instrukcja reagowania»: {autorzy}, «{tytul}», {wydanie}, {wersja}, ліцензія {licencja}. Цитати набрано звичайним шрифтом — оригінал складений великими літерами, слова без змін.",
    "Instrukcja MSWiA odsyła po lokalizacje punktów schronienia do urzędowej aplikacji {app}, prowadzonej przez Komendę Główną Państwowej Straży Pożarnej. Grota korzysta z tego samego wykazu PSP — różni się tym, że działa bez internetu, liczy czas dojścia i sprawdza położenie punktów.": "По розташування пунктів укриття інструкція МВС відсилає до офіційного застосунку {app}, який веде Головна комендатура Державної пожежної служби. Grota користується тим самим реєстром PSP — відрізняється тим, що працює без інтернету, рахує час дороги й перевіряє розташування пунктів.",
    "Decyzja podczas alarmu": "Рішення під час тривоги",
    "gdy zdążysz do punktu schronienia": "коли встигаєте до пункту укриття",
    "Jeżeli oznaczony punkt schronienia jest dostępny, droga do niego jest bezpieczna i masz czas – idź tam. Zabierz przygotowany wcześniej plecak ewakuacyjny oraz niezbędne leki. Nie używaj wind – poruszaj się wyłącznie schodami.": "Якщо позначений пункт укриття доступний, дорога до нього безпечна і ви маєте час – ідіть туди. Візьміть заздалегідь зібраний тривожний рюкзак і потрібні ліки. Не користуйтеся ліфтами – рухайтеся лише сходами.",
    "gdy droga zajęłaby za dużo czasu": "коли дорога зайняла б забагато часу",
    "Jeżeli dotarcie do punktu schronienia wymagałoby długiego przebywania na zewnątrz, nie próbuj za wszelką cenę tam dotrzeć. Pozostań w budynku, jeżeli ściany i stropy są solidne, bez widocznych uszkodzeń, albo wejdź do najbliższego takiego obiektu.": "Якщо дорога до пункту укриття означала б довге перебування назовні, не намагайтеся дістатися туди за будь-яку ціну. Залишіться в будівлі, якщо її стіни й перекриття міцні, без видимих пошкоджень, або зайдіть до найближчої такої будівлі.",
    "Wybór pomieszczenia": "Вибір приміщення",
    "zasada dwóch ścian": "правило двох стін",
    "Co najmniej dwie solidne ściany powinny znajdować się między Tobą a przestrzenią zewnętrzną.": "Між вами й зовнішнім простором мають бути щонайменше дві міцні стіни.",
    "jakie pomieszczenie wybrać": "яке приміщення вибрати",
    "Wybierz pomieszczenie: bez okien albo z jak najmniejszą powierzchnią przeszkleń, położone możliwie blisko środka budynku, oddalone od balkonów i ścian zewnętrznych, pozbawione kotła, piecyka gazowego, butli gazowych, dużych luster i ciężkich przedmiotów wiszących.": "Виберіть приміщення: без вікон або з якнайменшою площею скління, розташоване якомога ближче до середини будівлі, віддалене від балконів і зовнішніх стін, без котла, газової колонки, газових балонів, великих дзеркал і важких предметів, що висять.",
    "które pomieszczenia mogą się nadać": "які приміщення можуть підійти",
    "Odpowiednie mogą być: wewnętrzny korytarz, przedpokój lub przedsionek, łazienka, garderoba, komórka bez okien, piwnica, garaż podziemny. Łazienkę wybierz tylko wtedy, gdy nie ma okna, kotła ani piecyka gazowego. Klatka schodowa służy przede wszystkim do przemieszczania się – nie wybieraj jej jako miejsca schronienia, jeżeli ma duże okna.": "Підійти можуть: внутрішній коридор, передпокій або тамбур, ванна кімната, гардеробна, комора без вікон, підвал, підземний гараж. Ванну кімнату вибирайте лише тоді, коли в ній немає вікна, котла й газової колонки. Сходова клітка служить насамперед для пересування – не вибирайте її як укриття, якщо вона має великі вікна.",
    "Piwnica lub garaż podziemny": "Підвал або підземний гараж",
    "nie każde podziemie jest bezpieczne": "не кожне підземне приміщення безпечне",
    "Nie każde pomieszczenie podziemne jest bezpieczne. Jeżeli nie masz pewności, czy piwnica lub garaż są bezpieczne albo budynek ich nie posiada, pozostań w centralnym pomieszczeniu mieszkania lub domu.": "Не кожне підземне приміщення безпечне. Якщо ви не впевнені, чи підвал або гараж безпечні, або будівля їх не має, залишіться в центральному приміщенні квартири чи будинку.",
    "kiedy nie schodzić do piwnicy": "коли не спускатися в підвал",
    "Nie korzystaj z piwnicy, która ma: uszkodzony strop, pęknięcia konstrukcyjne, tylko jedno łatwe do zablokowania wyjście, przebiega przez nią instalacja gazowa.": "Не користуйтеся підвалом, який має: пошкоджене перекриття, конструкційні тріщини, лише один вихід, який легко заблокувати, або через який проходить газова мережа.",
    "gdzie stanąć w garażu podziemnym": "де стати в підземному гаражі",
    "W piwnicy lub w garażu podziemnym wybierz strefę: możliwie daleko od bramy i rampy wjazdowej, wolną od paliw, butli gazowych, chemikaliów i innych materiałów łatwopalnych, z dala od ładowarek i pomieszczeń technicznych. Nie uruchamiaj silników. Nie blokuj przejść ani dróg wyjazdowych.": "У підвалі або підземному гаражі виберіть зону: якомога далі від воріт і в'їзної рампи, вільну від пального, газових балонів, хімікатів та інших займистих матеріалів, подалі від зарядних пристроїв і технічних приміщень. Не запускайте двигунів. Не перекривайте проходів і виїзних шляхів.",
    "gdy jesteś w samochodzie": "коли ви в автомобілі",
    "Opuść pojazd i udaj się do najbliższego miejsca schronienia, zgodnie z przekazywanymi komunikatami i poleceniami służb. Samochód zaparkuj w sposób, który nie utrudnia przejazdu pojazdom służb ratowniczych i innym pojazdom uprzywilejowanym.": "Залиште транспортний засіб і прямуйте до найближчого укриття, відповідно до повідомлень і вказівок служб. Автомобіль припаркуйте так, щоб не заважати проїзду рятувальних та інших спеціальних автомобілів.",
    "Przygotuj się, zanim wystąpi zagrożenie": "Підготуйтеся, перш ніж виникне загроза",
    "zanim wystąpi zagrożenie": "перш ніж виникне загроза",
    "Przed wystąpieniem zagrożenia sprawdź drogę do punktu schronienia i sposób wejścia do niego. Wybierz co najmniej jeden punkt schronienia, jeżeli nie ma takiego w bliskiej okolicy, zaplanuj inne miejsce, gdzie się schronisz.": "Перш ніж виникне загроза, перевірте дорогу до пункту укриття й те, як до нього увійти. Виберіть щонайменше один пункт укриття, а якщо поблизу такого немає — заплануйте інше місце, де сховаєтеся.",
    "Piwnica lub garaż — sprawdź, zanim się tam schowasz": "Підвал або гараж — перевірте, перш ніж там сховатися",
    "Piwnica lub garaż podziemny odpowiednio przygotowane mogą zapewnić ochronę.": "Підвал або підземний гараж, належно підготовлені, можуть дати захист.",
    "Solidne ściany i stropy, bez widocznych uszkodzeń.": "Міцні стіни й перекриття, без видимих пошкоджень.",
    "Drożne wejście.": "Вільний вхід.",
    "Sprawna wentylacja.": "Справна вентиляція.",
    "Oświetlenie awaryjne.": "Аварійне освітлення.",
    "Bezpieczna droga wyjścia.": "Безпечний шлях виходу.",
    "Z miejsca schronienia i z przejść do niego usunięte: benzyna i inne paliwa, farby i rozpuszczalniki, butle gazowe, materiały pirotechniczne, duże ilości drewna, papieru i innych materiałów łatwopalnych.": "З укриття та з проходів до нього прибрано: бензин та інше пальне, фарби й розчинники, газові балони, піротехніку, великі кількості деревини, паперу та інших займистих матеріалів.",
    "Usunięte przedmioty, które mogą spaść, stłuc się albo zablokować wyjście.": "Прибрано предмети, які можуть упасти, розбитися або заблокувати вихід.",
    "Drogi prowadzące do miejsca schronienia oraz wyjścia podstawowe i wyjścia awaryjne pozostają drożne.": "Шляхи до укриття, а також основні та аварійні виходи лишаються вільними.",
    "wydanie z 25 września 2026": "видання від 25 вересня 2026 року",
    "Mapa": "Мапа",
    "Miejsca": "Місця",
    "TERAZ": "ЗАРАЗ",
    "Przygotuj": "Підготовка",
    "Zasady": "Правила",
    "Schronienie teraz": "Укриття зараз",
    "Moje miejsca": "Мої місця",
    "gdzie się schronić": "де сховатися",
    "prototyp · cała Polska": "прототип · уся Польща",
    "Jasna / ciemna mapa": "Світла / темна мапа",
    "Jasna albo ciemna mapa": "Світла або темна мапа",
  };
})(typeof window !== "undefined" ? window : globalThis);
