"""Build ONLY from manually reviewed decisions and already downloaded evidence.
No network, app imports, database, notification code or image transformation.
"""
import hashlib
import html
import json
import re
import shutil
from urllib.parse import urlsplit, urlunsplit
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / 'docs/aircraft-library'
RESEARCH = ROOT / 'test-out/aircraft-library-research'

def read(path):
    return json.loads(path.read_text(encoding='utf-8-sig'))

def plain(value):
    return ' '.join(html.unescape(re.sub(r'<[^>]*>', ' ', value or '')).split())

def build():
    decisions = read(DOCS / 'review-decisions.json')
    inventory = read(DOCS / 'inventory.json')
    assert set(decisions['rows']) | set(decisions['blocked']) == {r['type'] for r in inventory['models']}
    output = ROOT / 'frontend/assets/aircraft'
    output.mkdir(parents=True, exist_ok=True)
    photos = {}
    for code, (model, mode, aliases) in decisions['rows'].items():
        raw = read(RESEARCH / f'{code}.json')
        source = read(RESEARCH / f'{code}-source.json')
        assert raw['file_title'] == source['file_title'] and raw['sha1'] == source['sha1'], code
        meta = source['metadata']
        field = lambda key: meta.get(key, {}).get('value', '')
        license_name = plain(field('LicenseShortName'))
        assert license_name.startswith(('CC BY', 'CC0', 'Public domain', 'OGL')), (code, license_name)
        license_url = field('LicenseUrl') or raw['source_url']
        parts = urlsplit(license_url)
        if parts.hostname and parts.hostname.lower() in ('creativecommons.org', 'www.nationalarchives.gov.uk', 'nationalarchives.gov.uk'):
            license_url = urlunsplit(('https', parts.netloc.lower(), parts.path, parts.query, parts.fragment))
        assert license_url.startswith('https://'), (code, license_url)
        by = plain(field('Attribution') or field('Artist'))
        assert by, code
        if code == 'PZ3T': by = 'Ronnie Macdonald; source crop: FOX 52'
        image = RESEARCH / f'{code}.jpg'
        with Image.open(image) as im:
            assert im.format == 'JPEG', code
            width, height = im.size
            im.verify()
        sha = hashlib.sha256(image.read_bytes()).hexdigest()
        name = f'{code.lower()}-{sha[:12]}.jpg'
        shutil.copyfile(image, output / name)
        basis = re.findall(r'\{\{(PD[^}\n]+)\}\}', source['wikitext'])
        photos[code] = {'model': model, 'mode': mode, 'aliases': aliases,
            'src': f'assets/aircraft/{name}', 'author': by, 'license': license_name,
            'licenseUrl': license_url, 'sourceUrl': raw['source_url'],
            'sourceTitle': raw['file_title'], 'sourceSha1': source['sha1'],
            'sha256': sha, 'width': width, 'height': height,
            'licenseBasis': basis,
            'sourceCrop': bool(re.search(r'crop|altered', raw['file_title'], re.I)),
            'reviewedOn': decisions['reviewedOn']}
    catalog = {'version': 1, 'reviewedOn': decisions['reviewedOn'], 'photos': photos,
        'blocked': decisions['blocked'], 'identities': decisions['identities']}
    serial = json.dumps(catalog, ensure_ascii=False, indent=2)
    (DOCS / 'verified-photos.json').write_text(serial + '\n', encoding='utf-8')
    js = '/* Generated by scripts/build_aircraft_photo_library.py; photos have separate licenses. */\n'
    js += '(function(root){ const catalog = ' + serial + ';\n'
    js += 'if(typeof module!=="undefined" && module.exports) module.exports=catalog; else root.AircraftPhotoCatalog=catalog; })(globalThis);\n'
    (ROOT / 'frontend/aircraft-photo-catalog.js').write_text(js, encoding='utf-8')
    print(f'{len(photos)} reviewed photos; {sum(p["mode"]=="code" for p in photos.values())} code defaults; {len(decisions["blocked"])} blocked code')
    print(f'Photo assets: {sum((output/Path(p["src"]).name).stat().st_size for p in photos.values())/1024/1024:.2f} MiB; unchanged source thumbnails')

if __name__ == '__main__': build()
